In [8]:
import pandas
import pandas as pd
import numpy
import numpy as np
import random as rn
import functools
import re

In [9]:
'''
    Task 1:
        Check Pandas Version        
'''
print('Task 1:')  
print(pd.__version__)

Task 1:
0.23.0


In [10]:
'''
    Task 2:
    
    Numpy Array 
    Create three columns with Zero values            
'''
print('Task 2:')
dtype = [('Col1','int32'), ('Col2','float32'), ('Col3','float32')]
values = numpy.zeros(20, dtype=dtype)
index = ['Row'+str(i) for i in range(1, len(values)+1)]

df = pandas.DataFrame(values, index=index)

print(df)

df = pandas.DataFrame(values)
print(df)

Task 2:
       Col1  Col2  Col3
Row1      0   0.0   0.0
Row2      0   0.0   0.0
Row3      0   0.0   0.0
Row4      0   0.0   0.0
Row5      0   0.0   0.0
Row6      0   0.0   0.0
Row7      0   0.0   0.0
Row8      0   0.0   0.0
Row9      0   0.0   0.0
Row10     0   0.0   0.0
Row11     0   0.0   0.0
Row12     0   0.0   0.0
Row13     0   0.0   0.0
Row14     0   0.0   0.0
Row15     0   0.0   0.0
Row16     0   0.0   0.0
Row17     0   0.0   0.0
Row18     0   0.0   0.0
Row19     0   0.0   0.0
Row20     0   0.0   0.0
    Col1  Col2  Col3
0      0   0.0   0.0
1      0   0.0   0.0
2      0   0.0   0.0
3      0   0.0   0.0
4      0   0.0   0.0
5      0   0.0   0.0
6      0   0.0   0.0
7      0   0.0   0.0
8      0   0.0   0.0
9      0   0.0   0.0
10     0   0.0   0.0
11     0   0.0   0.0
12     0   0.0   0.0
13     0   0.0   0.0
14     0   0.0   0.0
15     0   0.0   0.0
16     0   0.0   0.0
17     0   0.0   0.0
18     0   0.0   0.0
19     0   0.0   0.0


In [11]:
'''
    Task 3:
        iLoc in Pandas
        Print first five rows
'''
print('Task 3:')
df = pandas.read_csv('data1.csv', sep=';', header=None)
print(df.iloc[:4]) # 0 - 4 = 5 values

Task 3:
                       0
0  capacity,score,length
1                1,10,30
2                2,20,30
3                3,30,40


In [12]:
'''
    Task 4:
        Create Random integer between 2 to 10 with 4 items        
'''
print('Task 4:')
values = np.random.randint(2, 10, size=4)
print(values)

Task 4:
[8 6 5 2]


In [13]:
'''
    Task 5:
        Create Random integer between 2 to 10 with 4 items
'''
print('Task 5:')
df = pd.DataFrame(np.random.randint(0, 100, size=(3, 2)), columns=list('xy'))
print(df)

Task 5:
    x   y
0  45  60
1  25  89
2  57  30


In [14]:
'''
    Task 6:
        Create Random integer between 2 to 10 with 4 items
'''
print('Task 6:')
df = pd.DataFrame(np.random.randint(0, 100, size=(2, 4)), columns=['A', 'B', 'C', 'D'])
print(df)

Task 6:
    A   B   C   D
0  94  30  10  68
1  20  66  21  93


In [15]:
'''
    Task 7:        
    
'''
print('Task 7:')
values = np.random.randint(5, size=(2, 4))
print(values)

Task 7:
[[0 4 0 0]
 [0 2 3 0]]


In [16]:
'''
    Task 8:        
        Numpy Random Seed 0
        
'''
print('Task 8:') 

Task 8:


In [17]:
'''
    Task 9:
        3 rows, 2 columns in pandas
            1st column = random between 10 to 20
            2nd column = random between 80 and 90
            3rd column = random between 40 and 50 
'''
print('Task 9:')  
dtype = [('One','int32'), ('Two','int32')]
values = np.zeros(3, dtype=dtype)
index = ['Row'+str(i) for i in range(1, 4)]

df = pandas.DataFrame(values, index=index)
print(df)

Task 9:
      One  Two
Row1    0    0
Row2    0    0
Row3    0    0


In [18]:
'''
    Task 10:
        Fill Random Science and Math Marks 
'''
print('Task 10:')  
dtype = [('Science','int32'), ('Maths','int32')]
values = np.zeros(3, dtype=dtype)
#values = np.random.randint(10, 100, size = (3, 5))
#print(type(dtype))
#values = np.random.randint(5, size=(2, 4))
print(values)
index = ['Row'+str(i) for i in range(1, 4)]

df = pandas.DataFrame(values, index=index)
print(df)

Task 10:
[(0, 0) (0, 0) (0, 0)]
      Science  Maths
Row1        0      0
Row2        0      0
Row3        0      0


In [19]:
'''
    Task 11:
        CSV to Dataframe (from_csv)
        Note: from_csv is Deprecated since version 0.21.0: Use pandas.read_csv() instead.
        
'''
print('Task 11:')  

csv = pd.DataFrame.from_csv('uk-500.csv')
print(csv)

Task 11:
              last_name                    company_name  \
first_name                                                
Aleshia      Tomkiewicz         Alan D Rosenburg Cpa Pc   
Evan          Zigomalas              Cap Gemini America   
France          Andrade             Elliott, John W Esq   
Ulysses       Mcwalters                  Mcmahan, Ben L   
Tyisha           Veness                  Champagne Room   
Eric              Rampy         Thompson, Michael C Esq   
Marg           Grasmick   Wrangle Hill Auto Auct & Slvg   
Laquita           Hisaw           In Communications Inc   
Lura           Manzella                 Bizerba Usa Inc   
Yuette           Klapec                       Max Video   
Fernanda         Writer            K & R Associates Inc   
Charlesetta         Erm                Cain, John M Esq   
Corrinne          Jaret               Sound Vision Corp   
Niesha            Bruch          Rowley/hansell Petetin   
Rueben        Gastellum   Industrial Engineerin

C:\ProgramData\Anaconda3.5\lib\site-packages\ipykernel_launcher.py:9: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  if __name__ == '__main__':


In [20]:
'''
    Task 12:
        CSV to Dataframe (from_csv)
        
'''
print('Task 12:')  
#df = df.from_csv(path, header, sep, index_col, parse_dates, encoding, tupleize_cols, infer_datetime_format)
df = pd.DataFrame.from_csv('uk-500.csv')
print(df)

Task 12:
              last_name                    company_name  \
first_name                                                
Aleshia      Tomkiewicz         Alan D Rosenburg Cpa Pc   
Evan          Zigomalas              Cap Gemini America   
France          Andrade             Elliott, John W Esq   
Ulysses       Mcwalters                  Mcmahan, Ben L   
Tyisha           Veness                  Champagne Room   
Eric              Rampy         Thompson, Michael C Esq   
Marg           Grasmick   Wrangle Hill Auto Auct & Slvg   
Laquita           Hisaw           In Communications Inc   
Lura           Manzella                 Bizerba Usa Inc   
Yuette           Klapec                       Max Video   
Fernanda         Writer            K & R Associates Inc   
Charlesetta         Erm                Cain, John M Esq   
Corrinne          Jaret               Sound Vision Corp   
Niesha            Bruch          Rowley/hansell Petetin   
Rueben        Gastellum   Industrial Engineerin

C:\ProgramData\Anaconda3.5\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  


In [21]:
'''
    Task 13:
        first 4 rows of CSV
        
'''
print('Task 13:') 
df = pandas.read_csv('data1.csv', sep=',')
print(df.shape) 
#print(df[2:14])
print(df.iloc[0:4,0:2])
#print(df[df.columns[0]])

Task 13:
(9, 3)
   capacity  score
0         1     10
1         2     20
2         3     30
3         3     40


In [22]:
'''
    Task 14:
        show even rows and first three columns
        
        
'''
print('Task 14:') 
df = pandas.read_csv('abc.csv', sep=',', encoding = "utf-8")
print(df.shape)
#print(df) 
#print(df[2:14])
print(df.iloc[::2, 0:3])    
#print(df.iloc[::1, 0:3])
#print(df[df.columns[0]])    

Task 14:
(7, 5)
  student  language  science
0   kumar        90       56
2   sammy        90       23
4   peter        30       56
6  carrol        50       90


In [23]:
'''
    Task 15:
        
        New columns as sum of all
        
'''
print('Task 15:') 
df = pandas.read_csv('abc.csv', sep=',', encoding = "utf-8")
print(df.shape)
print(df) 
df['total'] = df.sum(axis=1)

print(df)
#print(df[2:14])
#print(df.iloc[:,0:2])
#print(df[df.columns[0]]) 

Task 15:
(7, 5)
  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23
  student  language  science  maths  history  total
0   kumar        90       56     34       34    214
1   kevin        10       34     32       67    143
2   sammy        90       23     12       32    157
3  janice        20       67     90       45    222
4   peter        30       56     45       65    196
5    prem        90       45     45       34    214
6  carrol        50       90     45       23    208


In [24]:
'''
    Task 16:
        
        Delete Rows of one column where the value is less than 50
        
        
'''
print('Task 16:') 
df = pandas.read_csv('abc.csv', sep=',', encoding = "utf-8")
print(df.shape)
print(df) 

df = df[df.science > 50]
print(df)

Task 16:
(7, 5)
  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23
  student  language  science  maths  history
0   kumar        90       56     34       34
3  janice        20       67     90       45
4   peter        30       56     45       65
6  carrol        50       90     45       23


In [ ]:
'''
    Task 17:
        
        Delete with Query
        
        Note: Query doesn't work if your column has space in it
'''
print('Task 17:') 
df = pandas.read_csv('abc.csv', sep=',', encoding = "utf-8")
print(df.shape)
print(df) 

df = df.query('science > 45')
print(df)

Task 17:
(7, 5)
  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23


In [ ]:
'''
    Task 18:
        
        Skip single row
        
        
        
'''
print('Task 18:') 
df = pandas.read_csv('abc.csv', sep=',', encoding = "utf-8", skiprows=[5])
print(df.shape)
print(df)

In [ ]:
'''
    Task 19:
        
        Skip multiple rows
        
'''
print('Task 19:') 
df = pandas.read_csv('abc.csv', sep=',', encoding = "utf-8", skiprows=[1, 5, 7])
print(df.shape)
#print(df) 

#df = df[df[[1]] > 45]
print(df)

In [ ]:
'''
    Task 20:
        
        Select Column by Index
        
        Note:
            df[[1]] doesn't work in later Pandas
        
'''
print('Task 20:') 
df = pandas.read_csv('abc.csv', sep=',', encoding = "utf-8")
print(df.shape)
print(df) 

#df = df[int(df.columns[2]) > 45]
print(df)
print(type(df.columns[2]))

In [ ]:
'''
    Task 21:
        
        Skip rows
        
        Note:
            df[[1]] doesn't work in later Pandas
        
'''
print('Task 21:') 
df = pandas.read_csv('abc.csv', sep=',', encoding = "utf-8", skiprows=[0])
print(df.shape)
print(df) 

#df = df[int(df.columns[2]) > 45]
#print(df)
print(df.columns[2])

In [ ]:
'''
    Task 22:
        
        String to Dataframe
        
        Note:
            df[[1]] doesn't work in later Pandas
        
'''
print('Task 22:')
from io import StringIO

s = """
        1, 2
        3, 4
        5, 6
    """

df = pd.read_csv(StringIO(s), header=None)

print(df.shape)
print(df) 

#df = df[int(df.columns[2]) > 45]
#print(df)

In [ ]:
'''
    Task 23:
        
        New columns as max of other columns
        
        float to int used
'''
print('Task 23:') 
df = pandas.read_csv('abc.csv', sep=',', encoding = "utf-8")
print(df.shape)
df['sum'] = df.sum(axis=1)
df['max'] = df.max(axis=1)
df['min'] = df.min(axis=1)
df['average'] = df.mean(axis=1).astype(int)
print(df)    

In [ ]:
'''
    Task 24:
        
        New columns as max of other columns
        
        float to int used
        
        Math is considered more, so double the marks for maths
'''
def apply_math_special(row):
    return (row.maths * 2 + row.language / 2 + row.history / 3 + row.science) / 4                

print('Task 24:') 
df = pandas.read_csv('abc.csv', sep=',', encoding = "utf-8")
print(df.shape)
df['sum'] = df.sum(axis=1)
df['max'] = df.max(axis=1)
df['min'] = df.min(axis=1)
df['average'] = df.mean(axis=1).astype(int)
df['math_special'] = df.apply(apply_math_special, axis=1).astype(int)
print(df)    

In [ ]:
'''
    Task 25:
        
        New columns as max of other columns
        
        35 marks considered as pass 
        
        If the student fails in math, consider fail
        If the student passes in language and science, consider as pass
'''
def pass_one_subject(row):
    if(row.maths > 34):
        return 'Pass'
    if(row.language > 34 and row.science > 34):
        return 'Pass'
    
    return 'Fail'                

print('Task 25:') 
df = pandas.read_csv('abc.csv', sep=',', encoding = "utf-8")
print(df.shape)   

df['pass_one'] = df.apply(pass_one_subject, axis=1)
print(df)

In [ ]:
'''
    Task 26:
        
        fill with average
        
        df.fillna(df.mean, inplace=True)
            this will cause
                Fatal Python error: Cannot recover from stack overflow.
                Current thread 0x00008324 (most recent call first):
'''
print('Task 26:') 
df = pandas.read_csv('abc2.csv', sep=',', encoding = "utf-8")
print(df.shape)   
print(df)
df.fillna(df.mean(), inplace=True)

#df['pass_one'] = df.apply(pass_one_subject, axis=1)
print(df)    

In [ ]:
'''
    Task 28:
        
        New columns as sum of all
        
'''
print('Task 28:')
df = pd.DataFrame(np.random.rand(10, 5))
df.iloc[0:3, 0:4] = np.nan # throw in some na values
print(df)
df.loc[:, 'test'] = df.iloc[:, 2:].sum(axis=1)
print(df)  

In [ ]:
'''
    Task 29:
        Unicode issue and fix
    
'''
print('Task 29:') 
df = pandas.read_csv('score.csv', sep=',', encoding = "ISO-8859-1")
print(df.shape) 
#print(df[2:14])
#print(df.iloc[:,0:2])
#print(df[df.columns[0]])

In [ ]:
'''
    Task 27:
        
        fill with average
        
        df.fillna(df.mean, inplace=True)
            this will cause
                Fatal Python error: Cannot recover from stack overflow.
                Current thread 0x00008324 (most recent call first):
'''
print('Task 27:') 
df = pd.DataFrame(np.random.rand(3,4), columns=list("ABCD"))
print(df.shape)   
print(df)
df.fillna(df.mean(), inplace=True)

#df['pass_one'] = df.apply(pass_one_subject, axis=1)
print(df)   

In [ ]:
'''
    Task 30:
        Last 4 rows
'''
print('Task 30:')  
df = pandas.read_csv('data1.csv', sep=';') 
print(df[-4:])

In [ ]:
'''
    Task 31:
        Simple Data analysis

'''
print('Task 31:')  


In [ ]:
'''
    Task 32:
        get 3 and 4th row
'''
print('Task 32:')  
df = pandas.read_csv('data1.csv', sep=';') 
print(df[2:4])

In [ ]:
'''
    Task 33:
        Last 4th to 1st
'''
print('Task 33:')  
df = pandas.read_csv('data1.csv', sep=';') 
print(df[-4:-1])

In [ ]:
'''
    Task 34:
        iloc position slice
'''
print('Task 34:')  
df = pandas.read_csv('data1.csv', sep=';') 
print(df.iloc[1:9])

In [ ]:
'''
    Task 35:
        Loc - iloc - ix - at - iat 
'''
print('Task 35:')  
df = pandas.read_csv('data1.csv', sep=';')

In [ ]:
'''
    Task 36:
        Random data
'''
print('Task 36:')  
def xrange(x):
    return iter(range(x))

rnd_1  =  [ rn.randrange ( 1 , 20 )  for  x  in  xrange ( 1000 )] 
rnd_2  =  [ rn.randrange ( 1 , 20 )  for  x  in  xrange ( 1000 )] 
rnd_3  =  [ rn.randrange ( 1 , 20 )  for  x in  xrange ( 1000 )] 
date  =  pd . date_range ( '2012-4-10' ,  '2015-1-4' )
print(len(date))
data  =  pd . DataFrame ({ 'date' : date ,  'rnd_1' :  rnd_1 ,  'rnd_2' :  rnd_2 ,  'rnd_3' :  rnd_3 })

In [ ]:

'''
    Task 37:
    filter with the value comparison
'''
print('Task 37:')
below_20 = data[data['rnd_1'] < 20]    
print(below_20)

In [ ]:
'''
    Task 38:
       Filter between 5 and 10 on col 1 
'''
print('Task 38:') 
def xrange(x):
    return iter(range(x))
rnd_1  =  [ rn.randrange ( 1 , 20 )  for  x  in  xrange ( 1000 )] 
rnd_2  =  [ rn.randrange ( 1 , 20 )  for  x  in  xrange ( 1000 )] 
rnd_3  =  [ rn.randrange ( 1 , 20 )  for  x in  xrange ( 1000 )] 
date  =  pd . date_range ( '2012-4-10' ,  '2015-1-4' )
print(len(date))
data  =  pd . DataFrame ({ 'date' : date ,  'rnd_1' :  rnd_1 ,  'rnd_2' :  rnd_2 ,  'rnd_3' :  rnd_3 })
below_20 = data[data['rnd_1'] < 20]
ten_to_20 = data[(data['rnd_1'] >= 5) & (data['rnd_1'] < 10)]
#print(ten_to_20) 

In [ ]:
'''
    Task 39:
        15 to 20
        
'''
print('Task 39:')      
date  =  pd . date_range ( '2018-08-01' ,  '2018-08-15' )
date_count = len(date)

def fill_rand(start, end, count):
    return [rn.randrange(1, 20 ) for x in xrange( count )]

rnd_1 = fill_rand(1, 20, date_count) 
rnd_2 = fill_rand(1, 20, date_count) 
rnd_3 = fill_rand(1, 20, date_count)
#print(len(date))
data  =  pd . DataFrame ({ 'date' : date ,  'rnd_1' :  rnd_1 ,  'rnd_2' :  rnd_2 ,  'rnd_3' :  rnd_3 })
#print(len(date))
ten_to_20 = data[(data['rnd_1'] >= 15) & (data['rnd_1'] < 20)]
print(ten_to_20) 

In [ ]:
'''
    Task 40:
        15 to 33
        
'''
print('Task 40:')      
date  =  pd . date_range ( '2018-08-01' ,  '2018-08-15' )
date_count = len(date)

def fill_rand(start, end, count):
    return [rn.randrange(1, 20 ) for x in xrange( count )]

rnd_1 = fill_rand(1, 20, date_count) 
rnd_2 = fill_rand(1, 20, date_count) 
rnd_3 = fill_rand(1, 20, date_count)
#print(len(date))
data  =  pd . DataFrame ({ 'date' : date ,  'rnd_1' :  rnd_1 ,  'rnd_2' :  rnd_2 ,  'rnd_3' :  rnd_3 })
#print(len(date))
ten_to_20 = data[(data['rnd_1'] >= 15) & (data['rnd_1'] < 20)]
print(ten_to_20) 

In [ ]:
'''
    Task 41:
    set index
    
'''
print('Task 41:')  
date  =  pd . date_range ( '2018-08-01' ,  '2018-08-15' )
date_count = len(date)

def xrange(x):
    return iter(range(x))

def fill_rand(start, end, count):
    return [rn.randrange(1, 20 ) for x in xrange( count )]

rnd_1 = fill_rand(1, 20, date_count) 
rnd_2 = fill_rand(1, 20, date_count) 
rnd_3 = fill_rand(1, 20, date_count)
#print(len(date))
data  =  pd . DataFrame ({ 'date' : date ,  'rnd_1' :  rnd_1 ,  'rnd_2' :  rnd_2 ,  'rnd_3' :  rnd_3 })
filter_loc = data.loc[ 2 : 4 ,  [ 'rnd_2' ,  'date' ]]
print(filter_loc)

In [ ]:
'''
    Task 42:
       
'''
print('Task 42:')
date_date = data.set_index( 'date' ) 
print(date_date.head())  

In [ ]:
'''
    Task 43:
        Change columns based on other columns
'''
print('Task 43:') 
df = pd.DataFrame({
    'a' : [1,2,3,4], 
    'b' : [9,8,7,6],
    'c' : [11,12,13,14]
});
print(df) 

print('changing on one column')
# Change columns
df.loc[df.a >= 2,'b'] = 9
print(df)

In [ ]:
'''
    Task 44:
    Change multiple columns based on one column values   
'''
print('Task 44:')  
print('changing on multipe columns')
df.loc[df.a > 2,['b', 'c']] = 45
print(df)

In [ ]:
'''
    Task 45:
        Pandas Mask
'''
print('Task 45:')  
print(df)
df_mask = pd.DataFrame({
    'a' : [True] * 4, 
    'b' : [False] * 4,
    'c' : [True, False] * 2
})
print(df.where(df_mask,-1000))

In [ ]:
'''
    Task 46:
        
'''
print('Task 46:')
print(df)  
df['logic'] = np.where(df['a'] > 5, 'high', 'low')
print(df)

In [ ]:
'''
    Task 47:
        Student Marks (Pass or Fail)
'''
print('Task 47:')
marks_df = pd.DataFrame({
    'Language' : [60, 45, 78, 4], 
    'Math' : [90, 80, 23, 60],
    'Science' : [45, 90, 95, 20]
});
print(marks_df)
marks_df['language_grade'] = np.where(marks_df['Language'] >= 50, 'Pass', 'Fail')
marks_df['math_grade'] = np.where(marks_df['Math'] >= 50, 'Pass', 'Fail')
marks_df['science_grade'] = np.where(marks_df['Science'] >= 50, 'Pass', 'Fail')
print(marks_df)

In [ ]:
'''
    Actors by age and movies acted
'''


'''
    Task 48:
        Get passed grades
'''
print('Task 48:')  
marks_df = pd.DataFrame({
    'Language' : [60, 45, 78, 4], 
    'Math' : [90, 80, 23, 60],
    'Science' : [45, 90, 95, 20]
});
print(marks_df)
marks_df_passed_in_language = marks_df[marks_df.Language >=50 ]
print(marks_df_passed_in_language)

In [ ]:
'''
    Task 49:
        Students passed in Language and Math
        
'''
print('Task 49:')  
marks_df_passed_in_lang_math = marks_df[(marks_df.Language >=50) & (marks_df.Math >= 50)]
print(marks_df_passed_in_lang_math)

In [ ]:

'''
    Task 50:
        Students passed in Language and Science
'''
print('Task 50:')  
marks_df_passed_in_lang_and_sc = marks_df.loc[(marks_df.Language >=50) & (marks_df.Science >= 50)]
print(marks_df_passed_in_lang_and_sc)

In [ ]:
'''
    Task 51:
        Loc with Label oriented slicing
        
        possible error:
        pandas.errors.UnsortedIndexError
'''
print('Task 51:')
stars = {
    'age' : [31, 23, 65, 50],
    'movies' : [51, 23, 87, 200],
    'awards' : [42, 12, 4, 78]
    }
star_names = ['dhanush', 'simbu', 'kamal', 'vikram']
stars_df = pd.DataFrame(data=stars, index=[star_names])
print(stars_df)

In [ ]:
'''
    Task 52:
        iloc with positional slicing
'''
print('Task 52:')  
print(stars_df.iloc[1:3])

In [ ]:
'''
    Task 53:
        stars with names
'''
print('Task 40:')  
numbers = pd.DataFrame({
        'one' : [10, 50, 80, 40],
        'two' : [2, 6, 56, 45]
    },
    index = [12, 14, 16, 18])
print(numbers)

print('label between 12 and 16')
print(numbers.loc[12:16])

print('index between 1 and 3')
print(numbers.iloc[1:3])


In [ ]:
'''
    Task 54:
        stars with names
'''
print('Task 54:') 
stars = {
    'age' : [31, 23, 65, 50],
    'movies' : [51, 23, 87, 200],
    'awards' : [42, 12, 4, 78]
    }
star_names = ['dhanush', 'simbu', 'kamal', 'vikram']
stars_df = pd.DataFrame(data=stars, index=[star_names])
numbers = pd.DataFrame({
        'one' : [10, 50, 80, 40],
        'two' : [2, 6, 56, 45]
    },
    index = [12, 14, 16, 18])
print(numbers)

In [ ]:
'''
    Task 55:
        Row label selection
        Age is above 25 and movies above 25
'''
print('Task 55:')

age_movies_25 = stars_df[(stars_df.movies > 25 ) & (stars_df.age > 25)]  
print(age_movies_25)

In [ ]:
'''
    Task 56:
        stars in in certain ages
'''
print('Task 56:')  
custom_stars = stars_df[stars_df.age.isin([31, 65])]
print(custom_stars)

In [ ]:
'''
    Task 57:
        inverse opeartor
           !( above one.45 and below two.50 ) 
           
    
'''
print('Task 57:')  
print(numbers)
print(numbers[~( (numbers.one > 45) & (numbers.two < 50) )])

In [ ]:
'''
    Task 58:
        Extend a panal frame by transposing
        
'''
print('Task 58:')  

In [ ]:
'''
    Task 59:
        adding a new dimension
'''
print('Task 59:')  

In [ ]:
'''
    Task 60:
        Creating new Columns using Applymap
        Sides & applymap
'''
print('Task 60:')
sides_df = pd.DataFrame({
    'a' : [1, 1, 2, 4],
    'b' : [2, 1, 3, 4]
    })  
print(sides_df)
source_cols = sides_df.columns
print(source_cols)
new_cols = [str(x)+"_side" for x in source_cols]
side_category = {
    1 : 'North',
    2 : 'East',
    3 : 'South', 
    4 : 'West'
    }
sides_df[new_cols] = sides_df[source_cols].applymap(side_category.get)
print(sides_df)

In [ ]:
'''
    Task 61:
        Replacing some values with mean of the rest of a group
'''
print('Task 61:')  
df = pd.DataFrame({'A' : [1, 1, 2, 2], 'B' : [1, -1, 1, 2]})
print(df)

gb = df.groupby('A')

def replace(g):
    mask = g < 0
    g.loc[mask] = g[~mask].mean()
    return g

gbt = gb.transform(replace)

print(gbt)

In [ ]:
'''
    Task 62:
        Students passed in Language or Science (any one subject)
'''
print('Task 62:') 
marks_df = pd.DataFrame({
    'Language' : [60, 45, 78, 4], 
    'Math' : [90, 80, 23, 60],
    'Science' : [45, 90, 95, 20]
});
print(marks_df)
marks_df_passed_in_lang_or_sc = marks_df.loc[(marks_df.Language >=50) | (marks_df.Science >= 50)]
print(marks_df_passed_in_lang_or_sc) 

In [ ]:
'''
    Task 63:
   
        possible errors:
            TypeError: 'Series' objects are mutable, thus they cannot be hashed
    
    
'''
print('Task 63:')  
marks_df['passed_one_subject'] = 'Fail' 
marks_df.loc[(marks_df.Language >=50) , 'passed_one_subject'] = 'Pass'
print(marks_df)

In [ ]:
'''
    Task 64:
        argsort
        Select rows with data closest to certain value using argsort
        
'''
print('Task 64:')  
df = pd.DataFrame({
    "a": np.random.randint(0, 100, size=(5,)), 
    "b": np.random.randint(0, 70, size=(5,))
})
print(df)
par = 65
print('with argsort')
df1 = df.loc[(df.a-par).abs().argsort()]
print(df1)

print(df.loc[(df.b-2).abs().argsort()])

In [ ]:
'''
    Task 65:
        argsort with stars
        
        old stars (near by 50 age) argsort
'''
print('Task 65:')  
stars = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "movies": [2, 3, 90, 45, 34, 2] 
})
print(stars.loc[(stars.age - 50).abs().argsort()])

In [ ]:
'''
    Task 66:
        Argsort with actors
        young stars (near by 17)
'''
print('Task 66:')  
print(stars.loc[(stars.age - 17).abs().argsort()])

In [ ]:
'''
    Task 67:
        Binary operators
        
        Stars with
            younger than 19 - very young
            more movies acted
'''
print('Task 67:')
stars = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "movies": [22, 33, 90, 75, 34, 2] 
})  
print(stars)
print('Young and more movies acted')
young = stars.age < 30    
more_movies = stars.movies > 30
young_more = [young, more_movies]
young_more_Criteria = functools.reduce(lambda x, y : x & y, young_more)
print(stars[young_more_Criteria])

In [ ]:
'''
    Task 68:
        Young, Higher Salary, and Higher Position
'''
print('Task 68:')  
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8] 
})  
print(employees)
print('Young, Higher Salary, and Higher Position')
young = employees.age < 30
high_salary = employees.salary > 60
high_position = employees.grade > 6
young_salary_position = [young, high_salary, high_position]
young_salary_position_Criteria = functools.reduce(lambda x, y : x & y, young_salary_position)
print(employees[young_salary_position_Criteria])

In [ ]:
'''
    Task 69:
        Rename columns
        
        
'''
print('Task 69:')  
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8] 
})  
print(employees)
employees.rename(columns={'age': 'User Age', 'salary': 'Salary 2018'}, inplace=True)
print(employees)

In [ ]:
'''
    Task 70:
        Add a new column
        
        
'''
print('Task 70:')  
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8] 
})  
print(employees)
employees['group'] = pd.Series(np.random.randn(len(employees)))
print(employees)            

In [82]:
'''
    Task 71:
        Drop a column
        
        
'''
print('Task 71:')  
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8] 
})  
print(employees)
employees['group'] = pd.Series(np.random.randn(len(employees)))
print(employees)
employees.drop(employees.columns[[0]], axis=1, inplace = True)
print(employees)            

Task 71:
   age  grade  salary
0   17      7      75
1   50      8      33
2   24      9      90
3   45      2     175
4   65      7     134
5   18      8      78
   age  grade  salary     group
0   17      7      75 -1.101389
1   50      8      33 -0.285584
2   24      9      90  1.297441
3   45      2     175 -1.429696
4   65      7     134  0.684212
5   18      8      78  1.723453
   grade  salary     group
0      7      75 -1.101389
1      8      33 -0.285584
2      9      90  1.297441
3      2     175 -1.429696
4      7     134  0.684212
5      8      78  1.723453


In [83]:
'''
    Task 72:
        Drop multiple columns
'''
print('Task 72:')  
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8] 
})  
print(employees)
employees['group'] = pd.Series(np.random.randn(len(employees)))
print(employees)
employees.drop(employees.columns[[1, 2]], axis=1, inplace = True)
print(employees) 

Task 72:
   age  grade  salary
0   17      7      75
1   50      8      33
2   24      9      90
3   45      2     175
4   65      7     134
5   18      8      78
   age  grade  salary     group
0   17      7      75 -2.234927
1   50      8      33 -0.841366
2   24      9      90  2.028044
3   45      2     175  0.817154
4   65      7     134  0.694476
5   18      8      78 -0.427870
   age     group
0   17 -2.234927
1   50 -0.841366
2   24  2.028044
3   45  0.817154
4   65  0.694476
5   18 -0.427870


In [84]:
'''
    Task 73:
        Drop first and last column
        
'''
print('Task 73:')  
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees)
employees.drop(employees.columns[[0, len(employees.columns)-1]], axis=1, inplace = True)
print(employees)   

Task 73:
   age  grade  group  salary
0   17      7      1      75
1   50      8      1      33
2   24      9      2      90
3   45      2      2     175
4   65      7      2     134
5   18      8      1      78
   grade  group
0      7      1
1      8      1
2      9      2
3      2      2
4      7      2
5      8      1


In [85]:
'''
    Task 74:
        Delete by pop function
'''
print('Task 74:')  
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees)
group = employees.pop('group')
print(employees)
print(group)

Task 74:
   age  grade  group  salary
0   17      7      1      75
1   50      8      1      33
2   24      9      2      90
3   45      2      2     175
4   65      7      2     134
5   18      8      1      78
   age  grade  salary
0   17      7      75
1   50      8      33
2   24      9      90
3   45      2     175
4   65      7     134
5   18      8      78
0    1
1    1
2    2
3    2
4    2
5    1
Name: group, dtype: int64


In [86]:
'''
    Task 75:
    
        DataFrame.from_items
        
'''
print('Task 75:')  
df = pd.DataFrame.from_items([('A', [1, 2, 3]), ('B', [4, 5, 6]), ('C', [7,8, 9])], orient='index', columns=['one', 'two', 'three'])
print(df)

Task 75:
   one  two  three
A    1    2      3
B    4    5      6
C    7    8      9


In [87]:
'''
    Task 76:
        Pandas to list
        
'''
print('Task 76:')
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees)  
employees_list1 = list(employees.columns.values) 
employees_list2 = employees.values.tolist()
#employees_list = list(employees)
print(employees_list1)
print(employees_list2)

Task 76:
   age  grade  group  salary
0   17      7      1      75
1   50      8      1      33
2   24      9      2      90
3   45      2      2     175
4   65      7      2     134
5   18      8      1      78
['age', 'grade', 'group', 'salary']
[[17, 7, 1, 75], [50, 8, 1, 33], [24, 9, 2, 90], [45, 2, 2, 175], [65, 7, 2, 134], [18, 8, 1, 78]]


In [88]:
'''
    Task 77:
        Pandas rows to list
        
'''
print('Task 77:')
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees)  
employees_list2 = employees.values.tolist()
print(employees_list2)
print(type(employees_list2))
print(len(employees_list2))

Task 77:
   age  grade  group  salary
0   17      7      1      75
1   50      8      1      33
2   24      9      2      90
3   45      2      2     175
4   65      7      2     134
5   18      8      1      78
[[17, 7, 1, 75], [50, 8, 1, 33], [24, 9, 2, 90], [45, 2, 2, 175], [65, 7, 2, 134], [18, 8, 1, 78]]
<class 'list'>
6


In [89]:
'''
    Task 78:
        Pandas rows to array 
        
        Note: as_matrix is deprecated
'''
print('Task 78:')
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees)  
employees_list2 = employees.values
print(employees_list2)
print(type(employees_list2))
print(employees_list2.shape)

Task 78:
   age  grade  group  salary
0   17      7      1      75
1   50      8      1      33
2   24      9      2      90
3   45      2      2     175
4   65      7      2     134
5   18      8      1      78
[[ 17   7   1  75]
 [ 50   8   1  33]
 [ 24   9   2  90]
 [ 45   2   2 175]
 [ 65   7   2 134]
 [ 18   8   1  78]]
<class 'numpy.ndarray'>
(6, 4)


In [90]:
'''
    Task 79:
        Pandas rows to map 
'''
print('Task 79:')
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees)  
employees_list2 = map(list, employees.values)
print(employees_list2)
print(type(employees_list2))

Task 79:
   age  grade  group  salary
0   17      7      1      75
1   50      8      1      33
2   24      9      2      90
3   45      2      2     175
4   65      7      2     134
5   18      8      1      78
<class 'map'>


In [91]:
'''
    Task 80:
        Pandas rows to map 
'''
print('Task 80:')
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees)  
employees_list2 = list(map(list, employees.values))
print(employees_list2)
print(type(employees_list2))

Task 80:
   age  grade  group  salary
0   17      7      1      75
1   50      8      1      33
2   24      9      2      90
3   45      2      2     175
4   65      7      2     134
5   18      8      1      78
[[17, 7, 1, 75], [50, 8, 1, 33], [24, 9, 2, 90], [45, 2, 2, 175], [65, 7, 2, 134], [18, 8, 1, 78]]
<class 'list'>


In [92]:
'''
    Task 81:
    
    Drop duplicates
'''
print('Task 81:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)
users.drop_duplicates('id', inplace=True, keep='last')
print(users)

Task 81:
       city  count  id
0   Toronto      7   1
1  Montreal      8   1
2   Calgary      9   2
3  Montreal      2   2
4  Montreal      7   3
5    Ottawa      8   3
       city  count  id
1  Montreal      8   1
3  Montreal      2   2
5    Ottawa      8   3


In [93]:
'''
    Task 82:
    
    Selecting multiple columns
'''
print('Task 82:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)
users1 = users[['id', 'city']]
print(users1)

Task 82:
       city  count  id
0   Toronto      7   1
1  Montreal      8   1
2   Calgary      9   2
3  Montreal      2   2
4  Montreal      7   3
5    Ottawa      8   3
   id      city
0   1   Toronto
1   1  Montreal
2   2   Calgary
3   2  Montreal
4   3  Montreal
5   3    Ottawa


In [94]:
'''
    Task 83:
    
    Selecting multiple columns
'''
print('Task 83:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)
columns = ['id', 'count']
users1 = pd.DataFrame(users, columns=columns)
print(users1)

Task 83:
       city  count  id
0   Toronto      7   1
1  Montreal      8   1
2   Calgary      9   2
3  Montreal      2   2
4  Montreal      7   3
5    Ottawa      8   3
   id  count
0   1      7
1   1      8
2   2      9
3   2      2
4   3      7
5   3      8


In [95]:
'''
    Task 84:
    
        Row and Column Slicing
'''
print('Task 84:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)    
users1 = users.iloc[0:2, 1:3]
print(users1)

Task 84:
       city  count  id
0   Toronto      7   1
1  Montreal      8   1
2   Calgary      9   2
3  Montreal      2   2
4  Montreal      7   3
5    Ottawa      8   3
   count  id
0      7   1
1      8   1


In [96]:
'''
    Task 85:
    
        Iterating rows            
'''
print('Task 85:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)    
for index, row in users.iterrows():
    print(row['city'], "==>", row['count'])

Task 85:
       city  count  id
0   Toronto      7   1
1  Montreal      8   1
2   Calgary      9   2
3  Montreal      2   2
4  Montreal      7   3
5    Ottawa      8   3
Toronto ==> 7
Montreal ==> 8
Calgary ==> 9
Montreal ==> 2
Montreal ==> 7
Ottawa ==> 8


In [97]:
'''
    Task 86:
    
        Iterating tuples           
'''
print('Task 86:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)    
for row in users.itertuples(index=True, name='Pandas'):
    print(getattr(row, 'city'))
    
for row in users.itertuples(index=True, name='Pandas'):
    print(row.count)

Task 86:
       city  count  id
0   Toronto      7   1
1  Montreal      8   1
2   Calgary      9   2
3  Montreal      2   2
4  Montreal      7   3
5    Ottawa      8   3
Toronto
Montreal
Calgary
Montreal
Montreal
Ottawa
7
8
9
2
7
8


In [98]:
'''
    Task 87:
    
    Iterating rows and columns
        
'''
print('Task 87:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)    
for i, row in users.iterrows():
    for j, col in row.iteritems():    
        print(col)

Task 87:
       city  count  id
0   Toronto      7   1
1  Montreal      8   1
2   Calgary      9   2
3  Montreal      2   2
4  Montreal      7   3
5    Ottawa      8   3
Toronto
7
1
Montreal
8
1
Calgary
9
2
Montreal
2
2
Montreal
7
3
Ottawa
8
3


In [99]:
'''
    Task 88:
    List of Dictionary to Dataframe
    
'''
print('Task 88:')  
pointlist = [
                {'points': 50, 'time': '5:00', 'year': 2010}, 
                {'points': 25, 'time': '6:00', 'month': "february"}, 
                {'points':90, 'time': '9:00', 'month': 'january'}, 
                {'points_h1':20, 'month': 'june'}
            ]
print(pointlist)
pointDf = pd.DataFrame(pointlist)
print(pointDf)

pointDf1 = pd.DataFrame.from_dict(pointlist)
print(pointDf1)

Task 88:
[{'points': 50, 'time': '5:00', 'year': 2010}, {'points': 25, 'time': '6:00', 'month': 'february'}, {'points': 90, 'time': '9:00', 'month': 'january'}, {'points_h1': 20, 'month': 'june'}]
      month  points  points_h1  time    year
0       NaN    50.0        NaN  5:00  2010.0
1  february    25.0        NaN  6:00     NaN
2   january    90.0        NaN  9:00     NaN
3      june     NaN       20.0   NaN     NaN
      month  points  points_h1  time    year
0       NaN    50.0        NaN  5:00  2010.0
1  february    25.0        NaN  6:00     NaN
2   january    90.0        NaN  9:00     NaN
3      june     NaN       20.0   NaN     NaN


In [100]:
'''
    Task 89:
        
'''
print('Task 89:')
df = pd.DataFrame(np.random.randn(10,6))
# Make a few areas have NaN values
df.iloc[1:3,1] = np.nan
df.iloc[5,3] = np.nan
df.iloc[7:9,5] = np.nan
print(df)
df1 = df.isnull()
print(df1)

Task 89:
          0         1         2         3         4         5
0  0.867572 -0.879926 -0.468944 -1.440024  1.015430  0.271139
1 -0.769077       NaN -0.782085 -0.907081  0.737155 -0.115553
2 -1.154171       NaN  1.232303 -2.950458  0.948255  0.180885
3 -1.219973  1.209400 -1.411103 -0.978745 -0.124678  0.011744
4 -0.363351 -0.939732  0.271920 -1.187033 -0.805324 -0.270238
5 -0.050716 -1.543553  0.631182       NaN  0.822440  0.782168
6 -0.009563  0.036886 -1.088490 -0.173785 -1.548631  1.012639
7  0.113339  1.483705 -0.634299  0.770218 -1.922192       NaN
8  0.648116  1.209610  0.819374  0.196041 -0.044524       NaN
9 -0.025064 -0.597075 -0.202186 -1.272573 -1.164058  0.376195
       0      1      2      3      4      5
0  False  False  False  False  False  False
1  False   True  False  False  False  False
2  False   True  False  False  False  False
3  False  False  False  False  False  False
4  False  False  False  False  False  False
5  False  False  False   True  False  False
6

In [101]:
'''
    Task 90:
    
    Sum of all nan
    
'''
print('Task 90:')  
df = pd.DataFrame(np.random.randn(10,6))
# Make a few areas have NaN values
df.iloc[1:3,1] = np.nan
df.iloc[5,3] = np.nan
df.iloc[7:9,5] = np.nan
print(df)
print(df.isnull().sum())
print(df.isnull().sum(axis=1))
print(df.isnull().sum().tolist())

Task 90:
          0         1         2         3         4         5
0 -1.906510 -0.775088 -0.542778  0.155799  1.327626  0.872725
1  0.231823       NaN  1.568026 -0.659094  1.534931  0.502427
2 -0.153005       NaN -0.277420  1.197288  0.469800 -0.423028
3 -1.241355  0.334998  0.124630 -1.554444 -0.535457  0.600440
4 -0.465818  0.494810  0.665789 -1.037916  0.718561  1.670480
5  2.598779  0.891416  0.157395       NaN -1.297905  2.049617
6 -1.636774  0.372761  0.784692 -0.014923 -0.674421  0.349349
7 -0.672732 -1.507012 -0.533132  0.307051 -0.608392       NaN
8 -1.107422  0.029937 -0.396172  0.028875  1.370086       NaN
9  0.038605  0.462773 -1.198971  0.514100 -0.065473 -1.755313
0    0
1    2
2    0
3    1
4    0
5    2
dtype: int64
0    0
1    1
2    1
3    0
4    0
5    1
6    0
7    1
8    1
9    0
dtype: int64
[0, 2, 0, 1, 0, 2]


In [102]:
'''
    Task 91:
    
    Sum of all nan rowwise
    
'''
print('Task 91:')  
df = pd.DataFrame(np.random.randn(10,6))
# Make a few areas have NaN values
df.iloc[1:3,1] = np.nan
df.iloc[5,3] = np.nan
df.iloc[7:9,5] = np.nan
print(df)
print(df.isnull().sum(axis=1))

Task 91:
          0         1         2         3         4         5
0  0.091396 -0.099417  0.804931  0.912498  0.254322 -0.864371
1  0.553238       NaN  0.111771 -1.187903  0.712592 -0.549785
2 -1.283075       NaN  0.280043 -0.063850  0.086443 -0.988980
3 -0.525544 -1.165931 -1.738139 -0.138156 -1.366627 -0.733580
4  0.496183 -1.000675 -0.185416  0.164070  0.699662  0.332726
5 -0.340269  1.603991  0.783186       NaN -1.162359  0.533870
6 -0.428333  2.019640  0.733841 -0.738931 -2.637817 -1.096528
7  0.220660  0.095609  0.325437 -0.343544 -0.551402       NaN
8  0.347201 -0.238484 -1.485617 -0.513477 -0.332856       NaN
9 -0.290681  0.014988  0.351324 -0.245938  0.639185  0.262223
0    0
1    1
2    1
3    0
4    0
5    1
6    0
7    1
8    1
9    0
dtype: int64


In [103]:
'''
    Task 92:
    
    Sum of all nan as list
    
'''
print('Task 92:')  
df = pd.DataFrame(np.random.randn(10,6))
# Make a few areas have NaN values
df.iloc[1:3,1] = np.nan
df.iloc[5,3] = np.nan
df.iloc[7:9,5] = np.nan
print(df)
print(df.isnull().sum().tolist())

Task 92:
          0         1         2         3         4         5
0 -1.564206 -1.423871 -0.094469 -1.336205  1.357914 -0.845193
1  0.166684       NaN  2.558157  1.616207 -0.540373 -0.551791
2 -0.991121       NaN  0.181188 -0.850697 -0.989707  0.798264
3 -0.646711 -1.286375 -0.739950 -2.743003 -0.824337  0.779012
4  1.400090  0.682140  1.075032  1.635002 -0.920336 -0.588216
5 -0.022497  1.368350  0.007007       NaN -0.585850  0.742206
6 -1.378493 -1.081688  0.709706 -0.518872 -1.760325 -0.078149
7  0.915142  1.265809  1.962029 -0.225403  0.269005       NaN
8  0.216600  0.565914 -2.163026 -1.743336 -0.054566       NaN
9 -0.338333 -0.006250  1.099662 -0.919520 -0.051117 -1.443815
[0, 2, 0, 1, 0, 2]


In [104]:
'''
    Task 93:
        Change the order of columns
        
        Note:
            FutureWarning: '.reindex_axis' is deprecated and will be removed in a future version 
'''
print('Task 93:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)
users1 = users.reindex_axis(['city', 'count', 'id'], axis=1)
print(users1)

users2 = users.reindex(columns=['city', 'id', 'count'])
print(users2)

Task 93:
       city  count  id
0   Toronto      7   1
1  Montreal      8   1
2   Calgary      9   2
3  Montreal      2   2
4  Montreal      7   3
5    Ottawa      8   3
       city  count  id
0   Toronto      7   1
1  Montreal      8   1
2   Calgary      9   2
3  Montreal      2   2
4  Montreal      7   3
5    Ottawa      8   3
       city  id  count
0   Toronto   1      7
1  Montreal   1      8
2   Calgary   2      9
3  Montreal   2      2
4  Montreal   3      7
5    Ottawa   3      8


C:\Users\raja.raman\anaconda\lib\site-packages\ipykernel_launcher.py:16: FutureWarning: '.reindex_axis' is deprecated and will be removed in a future version. Use '.reindex' instead.
  app.launch_new_instance()


In [105]:
'''
    Task 94:
        Drop multiple rows
'''
print('Task 94:')
numbers = pd.DataFrame({
    "id": [1, 2, 3, 4, 5, 6], 
    "number": [10, 20, 30, 30, 23, 12]
    
})  
print(numbers)
numbers.drop(numbers.index[[0, 3, 5]], inplace=True)
print(numbers)

Task 94:
   id  number
0   1      10
1   2      20
2   3      30
3   4      30
4   5      23
5   6      12
   id  number
1   2      20
2   3      30
4   5      23


In [106]:
'''
    Task 95:
    
    Drop multiple rows by row name
'''
print('Task 95:')  
numbers = pd.DataFrame({
    "id": [1, 2, 3, 4, 5, 6], 
    "number": [10, 20, 30, 30, 23, 12]
    
}, index=['one', 'two', 'three', 'four', 'five', 'six'])  
print(numbers)
numbers1 = numbers.drop(['two','six'])
print(numbers1)
numbers2 = numbers.drop('two')
print(numbers2)

Task 95:
       id  number
one     1      10
two     2      20
three   3      30
four    4      30
five    5      23
six     6      12
       id  number
one     1      10
three   3      30
four    4      30
five    5      23
       id  number
one     1      10
three   3      30
four    4      30
five    5      23
six     6      12


In [107]:
'''
    Task 96:
    
    Drop a single row
        
'''
print('Task 96:')  

Task 96:


In [108]:
'''
    Task 97:
        Get the the odd row
'''
print('Task 97:')  
x = numpy.array([
                    [ 1,  2,  3,  4,  5],
                    [ 6,  7,  8,  9, 10],
                    [11, 12, 13, 14, 15],
                    [16, 17, 18, 19, 20]
                ]
    )
print(x)
print(x[::2])

Task 97:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [109]:
'''
    Task 98:
        Get the even columns
'''
print('Task 98:')  
x = numpy.array([
                    [ 1,  2,  3,  4,  5],
                    [ 6,  7,  8,  9, 10],
                    [11, 12, 13, 14, 15],
                    [16, 17, 18, 19, 20]
                ]
    )
print(x)
print(x[:, 1::2])

Task 98:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]]


In [110]:
'''
    Task 99:
        Odd rows and even columns
'''
print('Task 99:')  

x = numpy.array([
                    [ 1,  2,  3,  4,  5],
                    [ 6,  7,  8,  9, 10],
                    [11, 12, 13, 14, 15],
                    [16, 17, 18, 19, 20]
                ]
    )
print(x)
print(x[::2, 1::2])

Task 99:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 2  4]
 [12 14]]


In [111]:
'''
    Task 100:
    
    Drop duplicates
'''
print('Task 100:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)
users.drop_duplicates('id', inplace=True)
print(users)

Task 100:
       city  count  id
0   Toronto      7   1
1  Montreal      8   1
2   Calgary      9   2
3  Montreal      2   2
4  Montreal      7   3
5    Ottawa      8   3
       city  count  id
0   Toronto      7   1
2   Calgary      9   2
4  Montreal      7   3


In [112]:
'''
    Task 101:
    
    Drop all duplicates
'''
print('Task 101:')  
users = pd.DataFrame({
    "name": ['kevin', 'james', 'kumar', 'kevin', 'kevin', 'james'], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)
users.drop_duplicates('name', inplace=True, keep='last')
print(users)
users1 = users.drop_duplicates('name', keep=False)
print(users1)

Task 101:
       city  count   name
0   Toronto      7  kevin
1  Montreal      8  james
2   Calgary      9  kumar
3  Montreal      2  kevin
4  Montreal      7  kevin
5    Ottawa      8  james
       city  count   name
2   Calgary      9  kumar
4  Montreal      7  kevin
5    Ottawa      8  james
       city  count   name
2   Calgary      9  kumar
4  Montreal      7  kevin
5    Ottawa      8  james


In [113]:
'''
    Task 102:
        Multi Indexing:
'''
print('Task 102:')  

Task 102:


In [114]:
'''
    Task 103:
        Missing Data:
        Make A'th 3rd coulmn Nan
'''
print('Task 103:')  
df = pd.DataFrame(np.random.randn(6,1), index=pd.date_range('2013-08-01', periods=6, freq='B'), columns=list('A'))
print(df)
df.loc[df.index[3], 'A'] = np.nan
print(df)

Task 103:
                   A
2013-08-01 -1.189063
2013-08-02  0.684544
2013-08-05 -0.265494
2013-08-06  0.252164
2013-08-07  1.019576
2013-08-08 -0.210583
                   A
2013-08-01 -1.189063
2013-08-02  0.684544
2013-08-05 -0.265494
2013-08-06       NaN
2013-08-07  1.019576
2013-08-08 -0.210583


In [115]:
'''
    Task 104:
        
'''
print('Task 104:')
df1 = df.reindex(df.index[::-1]).ffill()
print(df1) 

Task 104:
                   A
2013-08-08 -0.210583
2013-08-07  1.019576
2013-08-06  1.019576
2013-08-05 -0.265494
2013-08-02  0.684544
2013-08-01 -1.189063


In [116]:
'''
    Task 105:
       Cumsum reset Nan
'''
print('Task 105:') 

Task 105:


In [119]:
'''
    Task 106:
'''
print('Task 106:')
df = pd.DataFrame([['http://wap.blah.com/xxx/id/11/someproduct_step2;jsessionid=....']],columns=['A'])
df1 = df['A'].str.findall("\\d\\d\\/(.*?)(;|\\?)",flags=re.IGNORECASE).apply(lambda x: pd.Series(x[0][0],index=['first']))
print(df1) 

Task 106:
               first
0  someproduct_step2


In [120]:
'''
    Task 107:
        Grouping:
'''
print('Task 107:')  
animals_df = pd.DataFrame({'animal': 'cat dog cat fish dog cat cat'.split(),
                   'size': list('SSMMMLL'),
                   'weight': [8, 10, 11, 1, 20, 12, 12],
                   'adult' : [False] * 5 + [True] * 2})
print(animals_df)

Task 107:
   adult animal size  weight
0  False    cat    S       8
1  False    dog    S      10
2  False    cat    M      11
3  False   fish    M       1
4  False    dog    M      20
5   True    cat    L      12
6   True    cat    L      12


In [121]:
'''
    Task 108:
        Basic Group by
'''
print('Task 108:')  
animals_df1 = animals_df.groupby('animal').apply(lambda x: x['size'][x['weight'].idxmax()])
print(animals_df1)

Task 108:
animal
cat     L
dog     M
fish    M
dtype: object


In [122]:
'''
    Task 109:
       Get Group
'''
print('Task 109:')  
cats = animals_df.groupby(['animal']).get_group('cat')
print(cats)

Task 109:
   adult animal size  weight
0  False    cat    S       8
2  False    cat    M      11
5   True    cat    L      12
6   True    cat    L      12


In [123]:
'''
    Task 110:
        
'''
print('Task 110:')
weights = animals_df.groupby(['weight']).get_group(20)  
print(weights)

Task 110:
   adult animal size  weight
4  False    dog    M      20


In [124]:
'''
    Task 111:
        
'''
print('Task 111:')  
def GrowUp(x):
    avg_weight =  sum(x[x['size'] == 'series1'].weight * 1.5)
    avg_weight += sum(x[x['size'] == 'M'].weight * 1.25)
    avg_weight += sum(x[x['size'] == 'L'].weight)
    avg_weight /= len(x)
    return pd.Series(['L',avg_weight,True], index=['size', 'weight', 'adult'])

animals_df = pd.DataFrame({'animal': 'cat dog cat fish dog cat cat'.split(),
                   'size': list('SSMMMLL'),
                   'weight': [8, 10, 11, 1, 20, 12, 12],
                   'adult' : [False] * 5 + [True] * 2})

gb = animals_df.groupby(['animal'])

expected_df = gb.apply(GrowUp)
print(expected_df)

Task 111:
       size   weight  adult
animal                     
cat       L   9.4375   True
dog       L  12.5000   True
fish      L   1.2500   True


In [127]:
'''
    Task 112:
        Expanding Apply:
'''
print('Task 112:')  
series1 = pd.Series([i / 100.0 for i in range(1,6)])
print(series1)
def CumRet(x,y):
    return x * (1 + y)
def Red(x):
    return functools.reduce(CumRet,x,1.0)
s2 = series1.expanding().apply(Red)
# s2 = series1.expanding().apply(Red, raw=True) # is not working
print(s2)

Task 112:
0    0.01
1    0.02
2    0.03
3    0.04
4    0.05
dtype: float64
0    1.010000
1    1.030200
2    1.061106
3    1.103550
4    1.158728
dtype: float64


In [128]:
'''
Task 113:
    Create Random integer between 0 to 100 with  10 itmes (2 rows, 5 columns)
'''
print('Task 113:')
df = pd.DataFrame(np.random.randint(0, 100, size=(3, 5)), columns=['Toronto', 'Ottawa', 'Calgary', 'Montreal', 'Quebec'])
print(df)

Task 113:
   Toronto  Ottawa  Calgary  Montreal  Quebec
0       48      52        8        65      36
1       85      90        4        60      99
2       42      81        5        89      38
