In [8]:
import pandas
import pandas as pd
import numpy
import numpy as np
import random as rn
import functools
import re

In [9]:
'''
    Task 1:
        Check Pandas Version        
'''
print('Task 1:')  
print(pd.__version__)

Task 1:
0.23.0


In [10]:
'''
    Task 2:
    
    Numpy Array 
    Create three columns with Zero values            
'''
print('Task 2:')
dtype = [('Col1','int32'), ('Col2','float32'), ('Col3','float32')]
values = numpy.zeros(20, dtype=dtype)
index = ['Row'+str(i) for i in range(1, len(values)+1)]

df = pandas.DataFrame(values, index=index)

print(df)

df = pandas.DataFrame(values)
print(df)

Task 2:
       Col1  Col2  Col3
Row1      0   0.0   0.0
Row2      0   0.0   0.0
Row3      0   0.0   0.0
Row4      0   0.0   0.0
Row5      0   0.0   0.0
Row6      0   0.0   0.0
Row7      0   0.0   0.0
Row8      0   0.0   0.0
Row9      0   0.0   0.0
Row10     0   0.0   0.0
Row11     0   0.0   0.0
Row12     0   0.0   0.0
Row13     0   0.0   0.0
Row14     0   0.0   0.0
Row15     0   0.0   0.0
Row16     0   0.0   0.0
Row17     0   0.0   0.0
Row18     0   0.0   0.0
Row19     0   0.0   0.0
Row20     0   0.0   0.0
    Col1  Col2  Col3
0      0   0.0   0.0
1      0   0.0   0.0
2      0   0.0   0.0
3      0   0.0   0.0
4      0   0.0   0.0
5      0   0.0   0.0
6      0   0.0   0.0
7      0   0.0   0.0
8      0   0.0   0.0
9      0   0.0   0.0
10     0   0.0   0.0
11     0   0.0   0.0
12     0   0.0   0.0
13     0   0.0   0.0
14     0   0.0   0.0
15     0   0.0   0.0
16     0   0.0   0.0
17     0   0.0   0.0
18     0   0.0   0.0
19     0   0.0   0.0


In [11]:
'''
    Task 3:
        iLoc in Pandas
        Print first five rows
'''
print('Task 3:')
df = pandas.read_csv('data1.csv', sep=';', header=None)
print(df.iloc[:4]) # 0 - 4 = 5 values

Task 3:
                       0
0  capacity,score,length
1                1,10,30
2                2,20,30
3                3,30,40


In [12]:
'''
    Task 4:
        Create Random integer between 2 to 10 with 4 items        
'''
print('Task 4:')
values = np.random.randint(2, 10, size=4)
print(values)

Task 4:
[8 6 5 2]


In [13]:
'''
    Task 5:
        Create Random integer between 2 to 10 with 4 items
'''
print('Task 5:')
df = pd.DataFrame(np.random.randint(0, 100, size=(3, 2)), columns=list('xy'))
print(df)

Task 5:
    x   y
0  45  60
1  25  89
2  57  30


In [14]:
'''
    Task 6:
        Create Random integer between 2 to 10 with 4 items
'''
print('Task 6:')
df = pd.DataFrame(np.random.randint(0, 100, size=(2, 4)), columns=['A', 'B', 'C', 'D'])
print(df)

Task 6:
    A   B   C   D
0  94  30  10  68
1  20  66  21  93


In [15]:
'''
    Task 7:        
    
'''
print('Task 7:')
values = np.random.randint(5, size=(2, 4))
print(values)

Task 7:
[[0 4 0 0]
 [0 2 3 0]]


In [16]:
'''
    Task 8:        
        Numpy Random Seed 0
        
'''
print('Task 8:') 

Task 8:


In [17]:
'''
    Task 9:
        3 rows, 2 columns in pandas
            1st column = random between 10 to 20
            2nd column = random between 80 and 90
            3rd column = random between 40 and 50 
'''
print('Task 9:')  
dtype = [('One','int32'), ('Two','int32')]
values = np.zeros(3, dtype=dtype)
index = ['Row'+str(i) for i in range(1, 4)]

df = pandas.DataFrame(values, index=index)
print(df)

Task 9:
      One  Two
Row1    0    0
Row2    0    0
Row3    0    0


In [18]:
'''
    Task 10:
        Fill Random Science and Math Marks 
'''
print('Task 10:')  
dtype = [('Science','int32'), ('Maths','int32')]
values = np.zeros(3, dtype=dtype)
#values = np.random.randint(10, 100, size = (3, 5))
#print(type(dtype))
#values = np.random.randint(5, size=(2, 4))
print(values)
index = ['Row'+str(i) for i in range(1, 4)]

df = pandas.DataFrame(values, index=index)
print(df)

Task 10:
[(0, 0) (0, 0) (0, 0)]
      Science  Maths
Row1        0      0
Row2        0      0
Row3        0      0


In [19]:
'''
    Task 11:
        CSV to Dataframe (from_csv)
        Note: from_csv is Deprecated since version 0.21.0: Use pandas.read_csv() instead.
        
'''
print('Task 11:')  

csv = pd.DataFrame.from_csv('uk-500.csv')
print(csv)

Task 11:
              last_name                    company_name  \
first_name                                                
Aleshia      Tomkiewicz         Alan D Rosenburg Cpa Pc   
Evan          Zigomalas              Cap Gemini America   
France          Andrade             Elliott, John W Esq   
Ulysses       Mcwalters                  Mcmahan, Ben L   
Tyisha           Veness                  Champagne Room   
Eric              Rampy         Thompson, Michael C Esq   
Marg           Grasmick   Wrangle Hill Auto Auct & Slvg   
Laquita           Hisaw           In Communications Inc   
Lura           Manzella                 Bizerba Usa Inc   
Yuette           Klapec                       Max Video   
Fernanda         Writer            K & R Associates Inc   
Charlesetta         Erm                Cain, John M Esq   
Corrinne          Jaret               Sound Vision Corp   
Niesha            Bruch          Rowley/hansell Petetin   
Rueben        Gastellum   Industrial Engineerin

C:\ProgramData\Anaconda3.5\lib\site-packages\ipykernel_launcher.py:9: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  if __name__ == '__main__':


In [20]:
'''
    Task 12:
        CSV to Dataframe (from_csv)
        
'''
print('Task 12:')  
#df = df.from_csv(path, header, sep, index_col, parse_dates, encoding, tupleize_cols, infer_datetime_format)
df = pd.DataFrame.from_csv('uk-500.csv')
print(df)

Task 12:
              last_name                    company_name  \
first_name                                                
Aleshia      Tomkiewicz         Alan D Rosenburg Cpa Pc   
Evan          Zigomalas              Cap Gemini America   
France          Andrade             Elliott, John W Esq   
Ulysses       Mcwalters                  Mcmahan, Ben L   
Tyisha           Veness                  Champagne Room   
Eric              Rampy         Thompson, Michael C Esq   
Marg           Grasmick   Wrangle Hill Auto Auct & Slvg   
Laquita           Hisaw           In Communications Inc   
Lura           Manzella                 Bizerba Usa Inc   
Yuette           Klapec                       Max Video   
Fernanda         Writer            K & R Associates Inc   
Charlesetta         Erm                Cain, John M Esq   
Corrinne          Jaret               Sound Vision Corp   
Niesha            Bruch          Rowley/hansell Petetin   
Rueben        Gastellum   Industrial Engineerin

C:\ProgramData\Anaconda3.5\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  


In [21]:
'''
    Task 13:
        first 4 rows of CSV
        
'''
print('Task 13:') 
df = pandas.read_csv('data1.csv', sep=',')
print(df.shape) 
#print(df[2:14])
print(df.iloc[0:4,0:2])
#print(df[df.columns[0]])

Task 13:
(9, 3)
   capacity  score
0         1     10
1         2     20
2         3     30
3         3     40


In [22]:
'''
    Task 14:
        show even rows and first three columns
        
        
'''
print('Task 14:') 
df = pandas.read_csv('abc.csv', sep=',', encoding = "utf-8")
print(df.shape)
#print(df) 
#print(df[2:14])
print(df.iloc[::2, 0:3])    
#print(df.iloc[::1, 0:3])
#print(df[df.columns[0]])    

Task 14:
(7, 5)
  student  language  science
0   kumar        90       56
2   sammy        90       23
4   peter        30       56
6  carrol        50       90


In [23]:
'''
    Task 15:
        
        New columns as sum of all
        
'''
print('Task 15:') 
df = pandas.read_csv('abc.csv', sep=',', encoding = "utf-8")
print(df.shape)
print(df) 
df['total'] = df.sum(axis=1)

print(df)
#print(df[2:14])
#print(df.iloc[:,0:2])
#print(df[df.columns[0]]) 

Task 15:
(7, 5)
  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23
  student  language  science  maths  history  total
0   kumar        90       56     34       34    214
1   kevin        10       34     32       67    143
2   sammy        90       23     12       32    157
3  janice        20       67     90       45    222
4   peter        30       56     45       65    196
5    prem        90       45     45       34    214
6  carrol        50       90     45       23    208


In [24]:
'''
    Task 16:
        
        Delete Rows of one column where the value is less than 50
        
        
'''
print('Task 16:') 
df = pandas.read_csv('abc.csv', sep=',', encoding = "utf-8")
print(df.shape)
print(df) 

df = df[df.science > 50]
print(df)

Task 16:
(7, 5)
  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23
  student  language  science  maths  history
0   kumar        90       56     34       34
3  janice        20       67     90       45
4   peter        30       56     45       65
6  carrol        50       90     45       23


In [25]:
'''
    Task 17:
        
        Delete with Query
        
        Note: Query doesn't work if your column has space in it
'''
print('Task 17:') 
df = pandas.read_csv('abc.csv', sep=',', encoding = "utf-8")
print(df.shape)
print(df) 

df = df.query('science > 45')
print(df)

Task 17:
(7, 5)
  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23
  student  language  science  maths  history
0   kumar        90       56     34       34
3  janice        20       67     90       45
4   peter        30       56     45       65
6  carrol        50       90     45       23


In [26]:
'''
    Task 18:
        
        Skip single row
        
        
        
'''
print('Task 18:') 
df = pandas.read_csv('abc.csv', sep=',', encoding = "utf-8", skiprows=[5])
print(df.shape)
print(df)

Task 18:
(6, 5)
  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4    prem        90       45     45       34
5  carrol        50       90     45       23


In [27]:
'''
    Task 19:
        
        Skip multiple rows
        
'''
print('Task 19:') 
df = pandas.read_csv('abc.csv', sep=',', encoding = "utf-8", skiprows=[1, 5, 7])
print(df.shape)
#print(df) 

#df = df[df[[1]] > 45]
print(df)

Task 19:
(4, 5)
  student  language  science  maths  history
0   kevin        10       34     32       67
1   sammy        90       23     12       32
2  janice        20       67     90       45
3    prem        90       45     45       34


In [28]:
'''
    Task 20:
        
        Select Column by Index
        
        Note:
            df[[1]] doesn't work in later Pandas
        
'''
print('Task 20:') 
df = pandas.read_csv('abc.csv', sep=',', encoding = "utf-8")
print(df.shape)
print(df) 

#df = df[int(df.columns[2]) > 45]
print(df)
print(type(df.columns[2]))

Task 20:
(7, 5)
  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23
  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23
<class 'str'>


In [29]:
'''
    Task 21:
        
        Skip rows
        
        Note:
            df[[1]] doesn't work in later Pandas
        
'''
print('Task 21:') 
df = pandas.read_csv('abc.csv', sep=',', encoding = "utf-8", skiprows=[0])
print(df.shape)
print(df) 

#df = df[int(df.columns[2]) > 45]
#print(df)
print(df.columns[2])

Task 21:
(6, 5)
    kumar  90  56  34  34.1
0   kevin  10  34  32    67
1   sammy  90  23  12    32
2  janice  20  67  90    45
3   peter  30  56  45    65
4    prem  90  45  45    34
5  carrol  50  90  45    23
56


In [30]:
'''
    Task 22:
        
        String to Dataframe
        
        Note:
            df[[1]] doesn't work in later Pandas
        
'''
print('Task 22:')
from io import StringIO

s = """
        1, 2
        3, 4
        5, 6
    """

df = pd.read_csv(StringIO(s), header=None)

print(df.shape)
print(df) 

#df = df[int(df.columns[2]) > 45]
#print(df)

Task 22:
(3, 2)
   0  1
0  1  2
1  3  4
2  5  6


In [31]:
'''
    Task 23:
        
        New columns as max of other columns
        
        float to int used
'''
print('Task 23:') 
df = pandas.read_csv('abc.csv', sep=',', encoding = "utf-8")
print(df.shape)
df['sum'] = df.sum(axis=1)
df['max'] = df.max(axis=1)
df['min'] = df.min(axis=1)
df['average'] = df.mean(axis=1).astype(int)
print(df)    

Task 23:
(7, 5)
  student  language  science  maths  history  sum  max  min  average
0   kumar        90       56     34       34  214  214   34       96
1   kevin        10       34     32       67  143  143   10       62
2   sammy        90       23     12       32  157  157   12       69
3  janice        20       67     90       45  222  222   20       98
4   peter        30       56     45       65  196  196   30       88
5    prem        90       45     45       34  214  214   34       96
6  carrol        50       90     45       23  208  208   23       92


In [32]:
'''
    Task 24:
        
        New columns as max of other columns
        
        float to int used
        
        Math is considered more, so double the marks for maths
'''
def apply_math_special(row):
    return (row.maths * 2 + row.language / 2 + row.history / 3 + row.science) / 4                

print('Task 24:') 
df = pandas.read_csv('abc.csv', sep=',', encoding = "utf-8")
print(df.shape)
df['sum'] = df.sum(axis=1)
df['max'] = df.max(axis=1)
df['min'] = df.min(axis=1)
df['average'] = df.mean(axis=1).astype(int)
df['math_special'] = df.apply(apply_math_special, axis=1).astype(int)
print(df)    

Task 24:
(7, 5)
  student  language  science  maths  history  sum  max  min  average  \
0   kumar        90       56     34       34  214  214   34       96   
1   kevin        10       34     32       67  143  143   10       62   
2   sammy        90       23     12       32  157  157   12       69   
3  janice        20       67     90       45  222  222   20       98   
4   peter        30       56     45       65  196  196   30       88   
5    prem        90       45     45       34  214  214   34       96   
6  carrol        50       90     45       23  208  208   23       92   

   math_special  
0            45  
1            31  
2            25  
3            68  
4            45  
5            47  
6            53  


In [33]:
'''
    Task 25:
        
        New columns as max of other columns
        
        35 marks considered as pass 
        
        If the student fails in math, consider fail
        If the student passes in language and science, consider as pass
'''
def pass_one_subject(row):
    if(row.maths > 34):
        return 'Pass'
    if(row.language > 34 and row.science > 34):
        return 'Pass'
    
    return 'Fail'                

print('Task 25:') 
df = pandas.read_csv('abc.csv', sep=',', encoding = "utf-8")
print(df.shape)   

df['pass_one'] = df.apply(pass_one_subject, axis=1)
print(df)

Task 25:
(7, 5)
  student  language  science  maths  history pass_one
0   kumar        90       56     34       34     Pass
1   kevin        10       34     32       67     Fail
2   sammy        90       23     12       32     Fail
3  janice        20       67     90       45     Pass
4   peter        30       56     45       65     Pass
5    prem        90       45     45       34     Pass
6  carrol        50       90     45       23     Pass


In [34]:
'''
    Task 26:
        
        fill with average
        
        df.fillna(df.mean, inplace=True)
            this will cause
                Fatal Python error: Cannot recover from stack overflow.
                Current thread 0x00008324 (most recent call first):
'''
print('Task 26:') 
df = pandas.read_csv('abc2.csv', sep=',', encoding = "utf-8")
print(df.shape)   
print(df)
df.fillna(df.mean(), inplace=True)

#df['pass_one'] = df.apply(pass_one_subject, axis=1)
print(df)    

Task 26:
(7, 5)
  student  language  science  maths  history
0   kumar        90     56.0   34.0       34
1   kevin        10      NaN   32.0       67
2   sammy        90     23.0   12.0       32
3  janice        20      NaN   90.0       45
4   peter        30     56.0   45.0       65
5    prem        90     45.0    NaN       34
6  carrol        50     90.0   45.0       23
  student  language  science  maths  history
0   kumar        90     56.0   34.0       34
1   kevin        10     54.0   32.0       67
2   sammy        90     23.0   12.0       32
3  janice        20     54.0   90.0       45
4   peter        30     56.0   45.0       65
5    prem        90     45.0   43.0       34
6  carrol        50     90.0   45.0       23


In [35]:
'''
    Task 28:
        
        New columns as sum of all
        
'''
print('Task 28:')
df = pd.DataFrame(np.random.rand(10, 5))
df.iloc[0:3, 0:4] = np.nan # throw in some na values
print(df)
df.loc[:, 'test'] = df.iloc[:, 2:].sum(axis=1)
print(df)  

Task 28:
          0         1         2         3         4
0       NaN       NaN       NaN       NaN  0.639537
1       NaN       NaN       NaN       NaN  0.658660
2       NaN       NaN       NaN       NaN  0.862719
3  0.875974  0.676573  0.247961  0.459989  0.032578
4  0.766880  0.968181  0.035912  0.106954  0.143374
5  0.024436  0.712699  0.044866  0.399964  0.477970
6  0.164762  0.149409  0.688910  0.389088  0.063072
7  0.410628  0.058644  0.350575  0.613522  0.279709
8  0.108157  0.674001  0.174866  0.074312  0.823326
9  0.479722  0.848397  0.857391  0.736149  0.952309
          0         1         2         3         4      test
0       NaN       NaN       NaN       NaN  0.639537  0.639537
1       NaN       NaN       NaN       NaN  0.658660  0.658660
2       NaN       NaN       NaN       NaN  0.862719  0.862719
3  0.875974  0.676573  0.247961  0.459989  0.032578  0.740527
4  0.766880  0.968181  0.035912  0.106954  0.143374  0.286240
5  0.024436  0.712699  0.044866  0.399964  0.47

In [36]:
'''
    Task 29:
        Unicode issue and fix
    
'''
print('Task 29:') 
df = pandas.read_csv('score.csv', sep=',', encoding = "ISO-8859-1")
print(df.shape) 
#print(df[2:14])
#print(df.iloc[:,0:2])
#print(df[df.columns[0]])

Task 29:
(16, 5)


In [37]:
'''
    Task 27:
        
        fill with average
        
        df.fillna(df.mean, inplace=True)
            this will cause
                Fatal Python error: Cannot recover from stack overflow.
                Current thread 0x00008324 (most recent call first):
'''
print('Task 27:') 
df = pd.DataFrame(np.random.rand(3,4), columns=list("ABCD"))
print(df.shape)   
print(df)
df.fillna(df.mean(), inplace=True)

#df['pass_one'] = df.apply(pass_one_subject, axis=1)
print(df)   

Task 27:
(3, 4)
          A         B         C         D
0  0.319515  0.639504  0.817963  0.374177
1  0.487329  0.347219  0.585821  0.135083
2  0.911735  0.103491  0.214837  0.830412
          A         B         C         D
0  0.319515  0.639504  0.817963  0.374177
1  0.487329  0.347219  0.585821  0.135083
2  0.911735  0.103491  0.214837  0.830412


In [38]:
'''
    Task 30:
        Last 4 rows
'''
print('Task 30:')  
df = pandas.read_csv('data1.csv', sep=';') 
print(df[-4:])

Task 30:
  capacity,score,length
5               7,10,23
6               3,20,22
7               8,20,11
8                2,30,2


In [39]:
'''
    Task 31:
        Simple Data analysis

'''
print('Task 31:')  


Task 31:


In [40]:
'''
    Task 32:
        get 3 and 4th row
'''
print('Task 32:')  
df = pandas.read_csv('data1.csv', sep=';') 
print(df[2:4])

Task 32:
  capacity,score,length
2               3,30,40
3               3,40,30


In [41]:
'''
    Task 33:
        Last 4th to 1st
'''
print('Task 33:')  
df = pandas.read_csv('data1.csv', sep=';') 
print(df[-4:-1])

Task 33:
  capacity,score,length
5               7,10,23
6               3,20,22
7               8,20,11


In [42]:
'''
    Task 34:
        iloc position slice
'''
print('Task 34:')  
df = pandas.read_csv('data1.csv', sep=';') 
print(df.iloc[1:9])

Task 34:
  capacity,score,length
1               2,20,30
2               3,30,40
3               3,40,30
4               2,30,40
5               7,10,23
6               3,20,22
7               8,20,11
8                2,30,2


In [43]:
'''
    Task 35:
        Loc - iloc - ix - at - iat 
'''
print('Task 35:')  
df = pandas.read_csv('data1.csv', sep=';')

Task 35:


In [44]:
'''
    Task 36:
        Random data
'''
print('Task 36:')  
def xrange(x):
    return iter(range(x))

rnd_1  =  [ rn.randrange ( 1 , 20 )  for  x  in  xrange ( 1000 )] 
rnd_2  =  [ rn.randrange ( 1 , 20 )  for  x  in  xrange ( 1000 )] 
rnd_3  =  [ rn.randrange ( 1 , 20 )  for  x in  xrange ( 1000 )] 
date  =  pd . date_range ( '2012-4-10' ,  '2015-1-4' )
print(len(date))
data  =  pd . DataFrame ({ 'date' : date ,  'rnd_1' :  rnd_1 ,  'rnd_2' :  rnd_2 ,  'rnd_3' :  rnd_3 })

Task 36:
1000


In [45]:

'''
    Task 37:
    filter with the value comparison
'''
print('Task 37:')
below_20 = data[data['rnd_1'] < 20]    
print(below_20)

Task 37:
          date  rnd_1  rnd_2  rnd_3
0   2012-04-10      4      9      4
1   2012-04-11      9     18      3
2   2012-04-12      7     16      4
3   2012-04-13     12     15     15
4   2012-04-14     11     11     19
5   2012-04-15     10      3     10
6   2012-04-16      7      7      6
7   2012-04-17      6      1      1
8   2012-04-18      9     16     12
9   2012-04-19     16      6     17
10  2012-04-20      7      6      6
11  2012-04-21     18     19      6
12  2012-04-22     19      4     10
13  2012-04-23     18     14     13
14  2012-04-24      3      5     19
15  2012-04-25     12     13     12
16  2012-04-26      6      3     16
17  2012-04-27      3      4     19
18  2012-04-28      5     16     19
19  2012-04-29      6      3     12
20  2012-04-30     11     10     14
21  2012-05-01      9     10     10
22  2012-05-02      3     14     18
23  2012-05-03      4     18     12
24  2012-05-04      2      1     19
25  2012-05-05      2      4      2
26  2012-05-06     

In [46]:
'''
    Task 38:
       Filter between 5 and 10 on col 1 
'''
print('Task 38:') 
def xrange(x):
    return iter(range(x))
rnd_1  =  [ rn.randrange ( 1 , 20 )  for  x  in  xrange ( 1000 )] 
rnd_2  =  [ rn.randrange ( 1 , 20 )  for  x  in  xrange ( 1000 )] 
rnd_3  =  [ rn.randrange ( 1 , 20 )  for  x in  xrange ( 1000 )] 
date  =  pd . date_range ( '2012-4-10' ,  '2015-1-4' )
print(len(date))
data  =  pd . DataFrame ({ 'date' : date ,  'rnd_1' :  rnd_1 ,  'rnd_2' :  rnd_2 ,  'rnd_3' :  rnd_3 })
below_20 = data[data['rnd_1'] < 20]
ten_to_20 = data[(data['rnd_1'] >= 5) & (data['rnd_1'] < 10)]
#print(ten_to_20) 

Task 38:
1000


In [47]:
'''
    Task 39:
        15 to 20
        
'''
print('Task 39:')      
date  =  pd . date_range ( '2018-08-01' ,  '2018-08-15' )
date_count = len(date)

def fill_rand(start, end, count):
    return [rn.randrange(1, 20 ) for x in xrange( count )]

rnd_1 = fill_rand(1, 20, date_count) 
rnd_2 = fill_rand(1, 20, date_count) 
rnd_3 = fill_rand(1, 20, date_count)
#print(len(date))
data  =  pd . DataFrame ({ 'date' : date ,  'rnd_1' :  rnd_1 ,  'rnd_2' :  rnd_2 ,  'rnd_3' :  rnd_3 })
#print(len(date))
ten_to_20 = data[(data['rnd_1'] >= 15) & (data['rnd_1'] < 20)]
print(ten_to_20) 

Task 39:
         date  rnd_1  rnd_2  rnd_3
0  2018-08-01     16     18      6
1  2018-08-02     16      2      3
3  2018-08-04     16     18     19
4  2018-08-05     15      5     15
6  2018-08-07     16     10     17
10 2018-08-11     16     17      8
14 2018-08-15     17      9     15


In [48]:
'''
    Task 40:
        15 to 33
        
'''
print('Task 40:')      
date  =  pd . date_range ( '2018-08-01' ,  '2018-08-15' )
date_count = len(date)

def fill_rand(start, end, count):
    return [rn.randrange(1, 20 ) for x in xrange( count )]

rnd_1 = fill_rand(1, 20, date_count) 
rnd_2 = fill_rand(1, 20, date_count) 
rnd_3 = fill_rand(1, 20, date_count)
#print(len(date))
data  =  pd . DataFrame ({ 'date' : date ,  'rnd_1' :  rnd_1 ,  'rnd_2' :  rnd_2 ,  'rnd_3' :  rnd_3 })
#print(len(date))
ten_to_20 = data[(data['rnd_1'] >= 15) & (data['rnd_1'] < 20)]
print(ten_to_20) 

Task 40:
        date  rnd_1  rnd_2  rnd_3
1 2018-08-02     16     16      2
5 2018-08-06     17     16      1
6 2018-08-07     15     15      2
8 2018-08-09     16     15     11


In [49]:
'''
    Task 41:
    set index
    
'''
print('Task 41:')  
date  =  pd . date_range ( '2018-08-01' ,  '2018-08-15' )
date_count = len(date)

def xrange(x):
    return iter(range(x))

def fill_rand(start, end, count):
    return [rn.randrange(1, 20 ) for x in xrange( count )]

rnd_1 = fill_rand(1, 20, date_count) 
rnd_2 = fill_rand(1, 20, date_count) 
rnd_3 = fill_rand(1, 20, date_count)
#print(len(date))
data  =  pd . DataFrame ({ 'date' : date ,  'rnd_1' :  rnd_1 ,  'rnd_2' :  rnd_2 ,  'rnd_3' :  rnd_3 })
filter_loc = data.loc[ 2 : 4 ,  [ 'rnd_2' ,  'date' ]]
print(filter_loc)

Task 41:
   rnd_2       date
2     12 2018-08-03
3      2 2018-08-04
4     12 2018-08-05


In [50]:
'''
    Task 42:
       
'''
print('Task 42:')
date_date = data.set_index( 'date' ) 
print(date_date.head())  

Task 42:
            rnd_1  rnd_2  rnd_3
date                           
2018-08-01     14      3     14
2018-08-02     11      2     18
2018-08-03      7     12     11
2018-08-04      9      2      7
2018-08-05     16     12      2


In [51]:
'''
    Task 43:
        Change columns based on other columns
'''
print('Task 43:') 
df = pd.DataFrame({
    'a' : [1,2,3,4], 
    'b' : [9,8,7,6],
    'c' : [11,12,13,14]
});
print(df) 

print('changing on one column')
# Change columns
df.loc[df.a >= 2,'b'] = 9
print(df)

Task 43:
   a  b   c
0  1  9  11
1  2  8  12
2  3  7  13
3  4  6  14
changing on one column
   a  b   c
0  1  9  11
1  2  9  12
2  3  9  13
3  4  9  14


In [52]:
'''
    Task 44:
    Change multiple columns based on one column values   
'''
print('Task 44:')  
print('changing on multipe columns')
df.loc[df.a > 2,['b', 'c']] = 45
print(df)

Task 44:
changing on multipe columns
   a   b   c
0  1   9  11
1  2   9  12
2  3  45  45
3  4  45  45


In [53]:
'''
    Task 45:
        Pandas Mask
'''
print('Task 45:')  
print(df)
df_mask = pd.DataFrame({
    'a' : [True] * 4, 
    'b' : [False] * 4,
    'c' : [True, False] * 2
})
print(df.where(df_mask,-1000))

Task 45:
   a   b   c
0  1   9  11
1  2   9  12
2  3  45  45
3  4  45  45
   a     b     c
0  1 -1000    11
1  2 -1000 -1000
2  3 -1000    45
3  4 -1000 -1000


In [54]:
'''
    Task 46:
        
'''
print('Task 46:')
print(df)  
df['logic'] = np.where(df['a'] > 5, 'high', 'low')
print(df)

Task 46:
   a   b   c
0  1   9  11
1  2   9  12
2  3  45  45
3  4  45  45
   a   b   c logic
0  1   9  11   low
1  2   9  12   low
2  3  45  45   low
3  4  45  45   low


In [55]:
'''
    Task 47:
        Student Marks (Pass or Fail)
'''
print('Task 47:')
marks_df = pd.DataFrame({
    'Language' : [60, 45, 78, 4], 
    'Math' : [90, 80, 23, 60],
    'Science' : [45, 90, 95, 20]
});
print(marks_df)
marks_df['language_grade'] = np.where(marks_df['Language'] >= 50, 'Pass', 'Fail')
marks_df['math_grade'] = np.where(marks_df['Math'] >= 50, 'Pass', 'Fail')
marks_df['science_grade'] = np.where(marks_df['Science'] >= 50, 'Pass', 'Fail')
print(marks_df)

Task 47:
   Language  Math  Science
0        60    90       45
1        45    80       90
2        78    23       95
3         4    60       20
   Language  Math  Science language_grade math_grade science_grade
0        60    90       45           Pass       Pass          Fail
1        45    80       90           Fail       Pass          Pass
2        78    23       95           Pass       Fail          Pass
3         4    60       20           Fail       Pass          Fail


In [56]:
'''
    Actors by age and movies acted
'''


'''
    Task 48:
        Get passed grades
'''
print('Task 48:')  
marks_df = pd.DataFrame({
    'Language' : [60, 45, 78, 4], 
    'Math' : [90, 80, 23, 60],
    'Science' : [45, 90, 95, 20]
});
print(marks_df)
marks_df_passed_in_language = marks_df[marks_df.Language >=50 ]
print(marks_df_passed_in_language)

Task 48:
   Language  Math  Science
0        60    90       45
1        45    80       90
2        78    23       95
3         4    60       20
   Language  Math  Science
0        60    90       45
2        78    23       95


In [57]:
'''
    Task 49:
        Students passed in Language and Math
        
'''
print('Task 49:')  
marks_df_passed_in_lang_math = marks_df[(marks_df.Language >=50) & (marks_df.Math >= 50)]
print(marks_df_passed_in_lang_math)

Task 49:
   Language  Math  Science
0        60    90       45


In [58]:

'''
    Task 50:
        Students passed in Language and Science
'''
print('Task 50:')  
marks_df_passed_in_lang_and_sc = marks_df.loc[(marks_df.Language >=50) & (marks_df.Science >= 50)]
print(marks_df_passed_in_lang_and_sc)

Task 50:
   Language  Math  Science
2        78    23       95


In [59]:
'''
    Task 51:
        Loc with Label oriented slicing
        
        possible error:
        pandas.errors.UnsortedIndexError
'''
print('Task 51:')
stars = {
    'age' : [31, 23, 65, 50],
    'movies' : [51, 23, 87, 200],
    'awards' : [42, 12, 4, 78]
    }
star_names = ['dhanush', 'simbu', 'kamal', 'vikram']
stars_df = pd.DataFrame(data=stars, index=[star_names])
print(stars_df)

Task 51:
         age  movies  awards
dhanush   31      51      42
simbu     23      23      12
kamal     65      87       4
vikram    50     200      78


In [60]:
'''
    Task 52:
        iloc with positional slicing
'''
print('Task 52:')  
print(stars_df.iloc[1:3])

Task 52:
       age  movies  awards
simbu   23      23      12
kamal   65      87       4


In [61]:
'''
    Task 53:
        stars with names
'''
print('Task 40:')  
numbers = pd.DataFrame({
        'one' : [10, 50, 80, 40],
        'two' : [2, 6, 56, 45]
    },
    index = [12, 14, 16, 18])
print(numbers)

print('label between 12 and 16')
print(numbers.loc[12:16])

print('index between 1 and 3')
print(numbers.iloc[1:3])


Task 40:
    one  two
12   10    2
14   50    6
16   80   56
18   40   45
label between 12 and 16
    one  two
12   10    2
14   50    6
16   80   56
index between 1 and 3
    one  two
14   50    6
16   80   56


In [62]:
'''
    Task 54:
        stars with names
'''
print('Task 54:') 
stars = {
    'age' : [31, 23, 65, 50],
    'movies' : [51, 23, 87, 200],
    'awards' : [42, 12, 4, 78]
    }
star_names = ['dhanush', 'simbu', 'kamal', 'vikram']
stars_df = pd.DataFrame(data=stars, index=[star_names])
numbers = pd.DataFrame({
        'one' : [10, 50, 80, 40],
        'two' : [2, 6, 56, 45]
    },
    index = [12, 14, 16, 18])
print(numbers)

Task 54:
    one  two
12   10    2
14   50    6
16   80   56
18   40   45


In [63]:
'''
    Task 55:
        Row label selection
        Age is above 25 and movies above 25
'''
print('Task 55:')

age_movies_25 = stars_df[(stars_df.movies > 25 ) & (stars_df.age > 25)]  
print(age_movies_25)

Task 55:
         age  movies  awards
dhanush   31      51      42
kamal     65      87       4
vikram    50     200      78


In [64]:
'''
    Task 56:
        stars in in certain ages
'''
print('Task 56:')  
custom_stars = stars_df[stars_df.age.isin([31, 65])]
print(custom_stars)

Task 56:
         age  movies  awards
dhanush   31      51      42
kamal     65      87       4


In [65]:
'''
    Task 57:
        inverse opeartor
           !( above one.45 and below two.50 ) 
           
    
'''
print('Task 57:')  
print(numbers)
print(numbers[~( (numbers.one > 45) & (numbers.two < 50) )])

Task 57:
    one  two
12   10    2
14   50    6
16   80   56
18   40   45
    one  two
12   10    2
16   80   56
18   40   45


In [66]:
'''
    Task 58:
        Extend a panal frame by transposing
        
'''
print('Task 58:')  

Task 58:


In [67]:
'''
    Task 59:
        adding a new dimension
'''
print('Task 59:')  

Task 59:


In [68]:
'''
    Task 60:
        Creating new Columns using Applymap
        Sides & applymap
'''
print('Task 60:')
sides_df = pd.DataFrame({
    'a' : [1, 1, 2, 4],
    'b' : [2, 1, 3, 4]
    })  
print(sides_df)
source_cols = sides_df.columns
print(source_cols)
new_cols = [str(x)+"_side" for x in source_cols]
side_category = {
    1 : 'North',
    2 : 'East',
    3 : 'South', 
    4 : 'West'
    }
sides_df[new_cols] = sides_df[source_cols].applymap(side_category.get)
print(sides_df)

Task 60:
   a  b
0  1  2
1  1  1
2  2  3
3  4  4
Index(['a', 'b'], dtype='object')
   a  b a_side b_side
0  1  2  North   East
1  1  1  North  North
2  2  3   East  South
3  4  4   West   West


In [69]:
'''
    Task 61:
        Replacing some values with mean of the rest of a group
'''
print('Task 61:')  
df = pd.DataFrame({'A' : [1, 1, 2, 2], 'B' : [1, -1, 1, 2]})
print(df)

gb = df.groupby('A')

def replace(g):
    mask = g < 0
    g.loc[mask] = g[~mask].mean()
    return g

gbt = gb.transform(replace)

print(gbt)

Task 61:
   A  B
0  1  1
1  1 -1
2  2  1
3  2  2
     B
0  1.0
1  1.0
2  1.0
3  2.0


In [70]:
'''
    Task 62:
        Students passed in Language or Science (any one subject)
'''
print('Task 62:') 
marks_df = pd.DataFrame({
    'Language' : [60, 45, 78, 4], 
    'Math' : [90, 80, 23, 60],
    'Science' : [45, 90, 95, 20]
});
print(marks_df)
marks_df_passed_in_lang_or_sc = marks_df.loc[(marks_df.Language >=50) | (marks_df.Science >= 50)]
print(marks_df_passed_in_lang_or_sc) 

Task 62:
   Language  Math  Science
0        60    90       45
1        45    80       90
2        78    23       95
3         4    60       20
   Language  Math  Science
0        60    90       45
1        45    80       90
2        78    23       95


In [71]:
'''
    Task 63:
   
        possible errors:
            TypeError: 'Series' objects are mutable, thus they cannot be hashed
    
    
'''
print('Task 63:')  
marks_df['passed_one_subject'] = 'Fail' 
marks_df.loc[(marks_df.Language >=50) , 'passed_one_subject'] = 'Pass'
print(marks_df)

Task 63:
   Language  Math  Science passed_one_subject
0        60    90       45               Pass
1        45    80       90               Fail
2        78    23       95               Pass
3         4    60       20               Fail


In [72]:
'''
    Task 64:
        argsort
        Select rows with data closest to certain value using argsort
        
'''
print('Task 64:')  
df = pd.DataFrame({
    "a": np.random.randint(0, 100, size=(5,)), 
    "b": np.random.randint(0, 70, size=(5,))
})
print(df)
par = 65
print('with argsort')
df1 = df.loc[(df.a-par).abs().argsort()]
print(df1)

print(df.loc[(df.b-2).abs().argsort()])

Task 64:
    a   b
0  24  56
1  75  57
2  69  32
3  13  53
4  36   0
with argsort
    a   b
2  69  32
1  75  57
4  36   0
0  24  56
3  13  53
    a   b
4  36   0
2  69  32
3  13  53
0  24  56
1  75  57


In [73]:
'''
    Task 65:
        argsort with stars
        
        old stars (near by 50 age) argsort
'''
print('Task 65:')  
stars = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "movies": [2, 3, 90, 45, 34, 2] 
})
print(stars.loc[(stars.age - 50).abs().argsort()])

Task 65:
   age  movies
1   50       3
3   45      45
4   65      34
2   24      90
5   18       2
0   17       2


In [74]:
'''
    Task 66:
        Argsort with actors
        young stars (near by 17)
'''
print('Task 66:')  
print(stars.loc[(stars.age - 17).abs().argsort()])

Task 66:
   age  movies
0   17       2
5   18       2
2   24      90
3   45      45
1   50       3
4   65      34


In [75]:
'''
    Task 67:
        Binary operators
        
        Stars with
            younger than 19 - very young
            more movies acted
'''
print('Task 67:')
stars = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "movies": [22, 33, 90, 75, 34, 2] 
})  
print(stars)
print('Young and more movies acted')
young = stars.age < 30    
more_movies = stars.movies > 30
young_more = [young, more_movies]
young_more_Criteria = functools.reduce(lambda x, y : x & y, young_more)
print(stars[young_more_Criteria])

Task 67:
   age  movies
0   17      22
1   50      33
2   24      90
3   45      75
4   65      34
5   18       2
Young and more movies acted
   age  movies
2   24      90


In [76]:
'''
    Task 68:
        Young, Higher Salary, and Higher Position
'''
print('Task 68:')  
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8] 
})  
print(employees)
print('Young, Higher Salary, and Higher Position')
young = employees.age < 30
high_salary = employees.salary > 60
high_position = employees.grade > 6
young_salary_position = [young, high_salary, high_position]
young_salary_position_Criteria = functools.reduce(lambda x, y : x & y, young_salary_position)
print(employees[young_salary_position_Criteria])

Task 68:
   age  salary  grade
0   17      75      7
1   50      33      8
2   24      90      9
3   45     175      2
4   65     134      7
5   18      78      8
Young, Higher Salary, and Higher Position
   age  salary  grade
0   17      75      7
2   24      90      9
5   18      78      8


In [77]:
'''
    Task 69:
        Rename columns
        
        
'''
print('Task 69:')  
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8] 
})  
print(employees)
employees.rename(columns={'age': 'User Age', 'salary': 'Salary 2018'}, inplace=True)
print(employees)

Task 69:
   age  salary  grade
0   17      75      7
1   50      33      8
2   24      90      9
3   45     175      2
4   65     134      7
5   18      78      8
   User Age  Salary 2018  grade
0        17           75      7
1        50           33      8
2        24           90      9
3        45          175      2
4        65          134      7
5        18           78      8


In [78]:
'''
    Task 70:
        Add a new column
        
        
'''
print('Task 70:')  
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8] 
})  
print(employees)
employees['group'] = pd.Series(np.random.randn(len(employees)))
print(employees)            

Task 70:
   age  salary  grade
0   17      75      7
1   50      33      8
2   24      90      9
3   45     175      2
4   65     134      7
5   18      78      8
   age  salary  grade     group
0   17      75      7  0.163091
1   50      33      8  1.473241
2   24      90      9 -0.045672
3   45     175      2 -1.028446
4   65     134      7 -1.246228
5   18      78      8  1.145015


In [79]:
'''
    Task 71:
        Drop a column
        
        
'''
print('Task 71:')  
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8] 
})  
print(employees)
employees['group'] = pd.Series(np.random.randn(len(employees)))
print(employees)
employees.drop(employees.columns[[0]], axis=1, inplace = True)
print(employees)            

Task 71:
   age  salary  grade
0   17      75      7
1   50      33      8
2   24      90      9
3   45     175      2
4   65     134      7
5   18      78      8
   age  salary  grade     group
0   17      75      7 -1.818764
1   50      33      8 -0.456546
2   24      90      9 -1.886270
3   45     175      2 -0.210496
4   65     134      7  0.687381
5   18      78      8 -1.323075
   salary  grade     group
0      75      7 -1.818764
1      33      8 -0.456546
2      90      9 -1.886270
3     175      2 -0.210496
4     134      7  0.687381
5      78      8 -1.323075


In [80]:
'''
    Task 72:
        Drop multiple columns
'''
print('Task 72:')  
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8] 
})  
print(employees)
employees['group'] = pd.Series(np.random.randn(len(employees)))
print(employees)
employees.drop(employees.columns[[1, 2]], axis=1, inplace = True)
print(employees) 

Task 72:
   age  salary  grade
0   17      75      7
1   50      33      8
2   24      90      9
3   45     175      2
4   65     134      7
5   18      78      8
   age  salary  grade     group
0   17      75      7 -1.111290
1   50      33      8 -0.455595
2   24      90      9  0.160526
3   45     175      2 -1.221311
4   65     134      7  0.134446
5   18      78      8  0.225626
   age     group
0   17 -1.111290
1   50 -0.455595
2   24  0.160526
3   45 -1.221311
4   65  0.134446
5   18  0.225626


In [81]:
'''
    Task 73:
        Drop first and last column
        
'''
print('Task 73:')  
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees)
employees.drop(employees.columns[[0, len(employees.columns)-1]], axis=1, inplace = True)
print(employees)   

Task 73:
   age  salary  grade  group
0   17      75      7      1
1   50      33      8      1
2   24      90      9      2
3   45     175      2      2
4   65     134      7      2
5   18      78      8      1
   salary  grade
0      75      7
1      33      8
2      90      9
3     175      2
4     134      7
5      78      8


In [82]:
'''
    Task 74:
        Delete by pop function
'''
print('Task 74:')  
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees)
group = employees.pop('group')
print(employees)
print(group)

Task 74:
   age  salary  grade  group
0   17      75      7      1
1   50      33      8      1
2   24      90      9      2
3   45     175      2      2
4   65     134      7      2
5   18      78      8      1
   age  salary  grade
0   17      75      7
1   50      33      8
2   24      90      9
3   45     175      2
4   65     134      7
5   18      78      8
0    1
1    1
2    2
3    2
4    2
5    1
Name: group, dtype: int64


In [83]:
'''
    Task 75:
    
        DataFrame.from_items
        
'''
print('Task 75:')  
df = pd.DataFrame.from_items([('A', [1, 2, 3]), ('B', [4, 5, 6]), ('C', [7,8, 9])], orient='index', columns=['one', 'two', 'three'])
print(df)

Task 75:
   one  two  three
A    1    2      3
B    4    5      6
C    7    8      9


C:\ProgramData\Anaconda3.5\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: from_items is deprecated. Please use DataFrame.from_dict(dict(items), ...) instead. DataFrame.from_dict(OrderedDict(items)) may be used to preserve the key order.
  


In [84]:
'''
    Task 76:
        Pandas to list
        
'''
print('Task 76:')
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees)  
employees_list1 = list(employees.columns.values) 
employees_list2 = employees.values.tolist()
#employees_list = list(employees)
print(employees_list1)
print(employees_list2)

Task 76:
   age  salary  grade  group
0   17      75      7      1
1   50      33      8      1
2   24      90      9      2
3   45     175      2      2
4   65     134      7      2
5   18      78      8      1
['age', 'salary', 'grade', 'group']
[[17, 75, 7, 1], [50, 33, 8, 1], [24, 90, 9, 2], [45, 175, 2, 2], [65, 134, 7, 2], [18, 78, 8, 1]]


In [85]:
'''
    Task 77:
        Pandas rows to list
        
'''
print('Task 77:')
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees)  
employees_list2 = employees.values.tolist()
print(employees_list2)
print(type(employees_list2))
print(len(employees_list2))

Task 77:
   age  salary  grade  group
0   17      75      7      1
1   50      33      8      1
2   24      90      9      2
3   45     175      2      2
4   65     134      7      2
5   18      78      8      1
[[17, 75, 7, 1], [50, 33, 8, 1], [24, 90, 9, 2], [45, 175, 2, 2], [65, 134, 7, 2], [18, 78, 8, 1]]
<class 'list'>
6


In [86]:
'''
    Task 78:
        Pandas rows to array 
        
        Note: as_matrix is deprecated
'''
print('Task 78:')
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees)  
employees_list2 = employees.values
print(employees_list2)
print(type(employees_list2))
print(employees_list2.shape)

Task 78:
   age  salary  grade  group
0   17      75      7      1
1   50      33      8      1
2   24      90      9      2
3   45     175      2      2
4   65     134      7      2
5   18      78      8      1
[[ 17  75   7   1]
 [ 50  33   8   1]
 [ 24  90   9   2]
 [ 45 175   2   2]
 [ 65 134   7   2]
 [ 18  78   8   1]]
<class 'numpy.ndarray'>
(6, 4)


In [87]:
'''
    Task 79:
        Pandas rows to map 
'''
print('Task 79:')
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees)  
employees_list2 = map(list, employees.values)
print(employees_list2)
print(type(employees_list2))

Task 79:
   age  salary  grade  group
0   17      75      7      1
1   50      33      8      1
2   24      90      9      2
3   45     175      2      2
4   65     134      7      2
5   18      78      8      1
<class 'map'>


In [88]:
'''
    Task 80:
        Pandas rows to map 
'''
print('Task 80:')
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees)  
employees_list2 = list(map(list, employees.values))
print(employees_list2)
print(type(employees_list2))

Task 80:
   age  salary  grade  group
0   17      75      7      1
1   50      33      8      1
2   24      90      9      2
3   45     175      2      2
4   65     134      7      2
5   18      78      8      1
[[17, 75, 7, 1], [50, 33, 8, 1], [24, 90, 9, 2], [45, 175, 2, 2], [65, 134, 7, 2], [18, 78, 8, 1]]
<class 'list'>


In [89]:
'''
    Task 81:
    
    Drop duplicates
'''
print('Task 81:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)
users.drop_duplicates('id', inplace=True, keep='last')
print(users)

Task 81:
   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
   id      city  count
1   1  Montreal      8
3   2  Montreal      2
5   3    Ottawa      8


In [90]:
'''
    Task 82:
    
    Selecting multiple columns
'''
print('Task 82:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)
users1 = users[['id', 'city']]
print(users1)

Task 82:
   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
   id      city
0   1   Toronto
1   1  Montreal
2   2   Calgary
3   2  Montreal
4   3  Montreal
5   3    Ottawa


In [91]:
'''
    Task 83:
    
    Selecting multiple columns
'''
print('Task 83:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)
columns = ['id', 'count']
users1 = pd.DataFrame(users, columns=columns)
print(users1)

Task 83:
   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
   id  count
0   1      7
1   1      8
2   2      9
3   2      2
4   3      7
5   3      8


In [92]:
'''
    Task 84:
    
        Row and Column Slicing
'''
print('Task 84:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)    
users1 = users.iloc[0:2, 1:3]
print(users1)

Task 84:
   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
       city  count
0   Toronto      7
1  Montreal      8


In [93]:
'''
    Task 85:
    
        Iterating rows            
'''
print('Task 85:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)    
for index, row in users.iterrows():
    print(row['city'], "==>", row['count'])

Task 85:
   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
Toronto ==> 7
Montreal ==> 8
Calgary ==> 9
Montreal ==> 2
Montreal ==> 7
Ottawa ==> 8


In [94]:
'''
    Task 86:
    
        Iterating tuples           
'''
print('Task 86:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)    
for row in users.itertuples(index=True, name='Pandas'):
    print(getattr(row, 'city'))
    
for row in users.itertuples(index=True, name='Pandas'):
    print(row.count)

Task 86:
   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
Toronto
Montreal
Calgary
Montreal
Montreal
Ottawa
7
8
9
2
7
8


In [95]:
'''
    Task 87:
    
    Iterating rows and columns
        
'''
print('Task 87:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)    
for i, row in users.iterrows():
    for j, col in row.iteritems():    
        print(col)

Task 87:
   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
1
Toronto
7
1
Montreal
8
2
Calgary
9
2
Montreal
2
3
Montreal
7
3
Ottawa
8


In [96]:
'''
    Task 88:
    List of Dictionary to Dataframe
    
'''
print('Task 88:')  
pointlist = [
                {'points': 50, 'time': '5:00', 'year': 2010}, 
                {'points': 25, 'time': '6:00', 'month': "february"}, 
                {'points':90, 'time': '9:00', 'month': 'january'}, 
                {'points_h1':20, 'month': 'june'}
            ]
print(pointlist)
pointDf = pd.DataFrame(pointlist)
print(pointDf)

pointDf1 = pd.DataFrame.from_dict(pointlist)
print(pointDf1)

Task 88:
[{'points': 50, 'time': '5:00', 'year': 2010}, {'points': 25, 'time': '6:00', 'month': 'february'}, {'points': 90, 'time': '9:00', 'month': 'january'}, {'points_h1': 20, 'month': 'june'}]
      month  points  points_h1  time    year
0       NaN    50.0        NaN  5:00  2010.0
1  february    25.0        NaN  6:00     NaN
2   january    90.0        NaN  9:00     NaN
3      june     NaN       20.0   NaN     NaN
      month  points  points_h1  time    year
0       NaN    50.0        NaN  5:00  2010.0
1  february    25.0        NaN  6:00     NaN
2   january    90.0        NaN  9:00     NaN
3      june     NaN       20.0   NaN     NaN


In [97]:
'''
    Task 89:
        
'''
print('Task 89:')
df = pd.DataFrame(np.random.randn(10,6))
# Make a few areas have NaN values
df.iloc[1:3,1] = np.nan
df.iloc[5,3] = np.nan
df.iloc[7:9,5] = np.nan
print(df)
df1 = df.isnull()
print(df1)

Task 89:
          0         1         2         3         4         5
0  0.368119 -0.618385 -0.177485 -1.688823  0.282728 -1.604442
1  0.197708       NaN  1.149004  1.214974  2.106309  3.029326
2  0.919111       NaN  0.967708  0.755446  1.689067  1.909511
3 -0.147434  0.597057 -1.209589  0.260891 -0.201666  0.395529
4  1.106504 -0.658631 -1.078996  0.868128 -1.007905  0.551846
5  0.288789 -0.854239 -0.630745       NaN  1.550963  1.011978
6 -1.261622  1.465020 -1.497316 -0.743806  1.712161 -0.180887
7  0.701357  0.514685 -1.521904  1.205764  1.188268       NaN
8  1.560825 -1.254417  0.842408 -1.631466  1.020026       NaN
9 -0.679136  1.022602 -0.987331  0.056432  0.729207 -0.396791
       0      1      2      3      4      5
0  False  False  False  False  False  False
1  False   True  False  False  False  False
2  False   True  False  False  False  False
3  False  False  False  False  False  False
4  False  False  False  False  False  False
5  False  False  False   True  False  False
6

In [98]:
'''
    Task 90:
    
    Sum of all nan
    
'''
print('Task 90:')  
df = pd.DataFrame(np.random.randn(10,6))
# Make a few areas have NaN values
df.iloc[1:3,1] = np.nan
df.iloc[5,3] = np.nan
df.iloc[7:9,5] = np.nan
print(df)
print(df.isnull().sum())
print(df.isnull().sum(axis=1))
print(df.isnull().sum().tolist())

Task 90:
          0         1         2         3         4         5
0 -0.646320 -1.176296 -1.376492  0.297095 -1.039141 -2.167651
1 -0.057257       NaN  1.418066 -0.323321  0.882381 -1.053136
2 -0.153016       NaN  1.259651 -0.956823 -2.840020  0.174007
3  1.506137  1.110249 -0.209510  0.148389 -1.446699 -0.515826
4 -0.094109  1.628408 -0.709620 -0.057702  1.873879  0.078500
5 -0.067984 -0.695959  0.508124       NaN -1.022061 -1.934815
6 -0.678744 -0.374348  0.614621  0.257375 -0.551115  0.248703
7  0.871593 -0.306885 -1.405786 -0.813769 -0.768716       NaN
8 -2.299637  0.512105  0.297790  1.110300 -0.643319       NaN
9  1.125623 -0.615287 -0.551879  0.167211  1.087697 -0.368400
0    0
1    2
2    0
3    1
4    0
5    2
dtype: int64
0    0
1    1
2    1
3    0
4    0
5    1
6    0
7    1
8    1
9    0
dtype: int64
[0, 2, 0, 1, 0, 2]


In [99]:
'''
    Task 91:
    
    Sum of all nan rowwise
    
'''
print('Task 91:')  
df = pd.DataFrame(np.random.randn(10,6))
# Make a few areas have NaN values
df.iloc[1:3,1] = np.nan
df.iloc[5,3] = np.nan
df.iloc[7:9,5] = np.nan
print(df)
print(df.isnull().sum(axis=1))

Task 91:
          0         1         2         3         4         5
0 -1.450815 -1.455864  0.488327 -1.152947  0.292693 -0.799981
1 -0.972923       NaN  0.118029  0.314374 -0.196083  0.837908
2 -0.883625       NaN  0.566772 -0.146879  0.092887 -0.581539
3  0.791767 -0.701232  0.251238  0.603868  0.569165  0.681942
4 -0.231014  0.629848 -0.261716  0.798203  0.446231  1.002701
5 -1.495765  2.182456 -1.395450       NaN -0.420351  1.893818
6 -1.928687 -0.231873 -0.573793 -0.435147  0.375527 -0.984068
7  0.260411 -0.953879 -1.456337  1.891719  1.663261       NaN
8  0.841930  0.616432  0.753801 -2.292130  0.221986       NaN
9  1.523449  1.084963  0.005979  0.914671  1.095556 -1.586332
0    0
1    1
2    1
3    0
4    0
5    1
6    0
7    1
8    1
9    0
dtype: int64


In [100]:
'''
    Task 92:
    
    Sum of all nan as list
    
'''
print('Task 92:')  
df = pd.DataFrame(np.random.randn(10,6))
# Make a few areas have NaN values
df.iloc[1:3,1] = np.nan
df.iloc[5,3] = np.nan
df.iloc[7:9,5] = np.nan
print(df)
print(df.isnull().sum().tolist())

Task 92:
          0         1         2         3         4         5
0 -1.194023 -0.415784  0.678128  0.262107  2.690122  1.696489
1  0.806665       NaN  0.601253 -1.368084  1.475203 -1.147096
2 -0.361020       NaN  2.097511 -0.154594  0.966872 -0.345844
3  2.164456  1.101059  0.362580  0.077831  0.874325  0.758031
4 -0.832723 -1.063599 -0.972769 -0.089096  1.652491 -1.569990
5  0.138751 -0.599608  1.740047       NaN  1.903410  0.723574
6 -1.472464 -2.952072 -2.597340  0.314686 -0.927545  1.777650
7  0.199804 -0.161187 -0.183639  0.045560 -0.549197       NaN
8 -2.215744  0.128328 -0.267326 -0.249821 -3.413820       NaN
9  0.993981  0.949607 -0.060822  0.019378 -1.314542  1.224525
[0, 2, 0, 1, 0, 2]


In [101]:
'''
    Task 93:
        Change the order of columns
        
        Note:
            FutureWarning: '.reindex_axis' is deprecated and will be removed in a future version 
'''
print('Task 93:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)
users1 = users.reindex_axis(['city', 'count', 'id'], axis=1)
print(users1)

users2 = users.reindex(columns=['city', 'id', 'count'])
print(users2)

Task 93:
   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
       city  count  id
0   Toronto      7   1
1  Montreal      8   1
2   Calgary      9   2
3  Montreal      2   2
4  Montreal      7   3
5    Ottawa      8   3
       city  id  count
0   Toronto   1      7
1  Montreal   1      8
2   Calgary   2      9
3  Montreal   2      2
4  Montreal   3      7
5    Ottawa   3      8


C:\ProgramData\Anaconda3.5\lib\site-packages\ipykernel_launcher.py:16: FutureWarning: '.reindex_axis' is deprecated and will be removed in a future version. Use '.reindex' instead.
  app.launch_new_instance()


In [102]:
'''
    Task 94:
        Drop multiple rows
'''
print('Task 94:')
numbers = pd.DataFrame({
    "id": [1, 2, 3, 4, 5, 6], 
    "number": [10, 20, 30, 30, 23, 12]
    
})  
print(numbers)
numbers.drop(numbers.index[[0, 3, 5]], inplace=True)
print(numbers)

Task 94:
   id  number
0   1      10
1   2      20
2   3      30
3   4      30
4   5      23
5   6      12
   id  number
1   2      20
2   3      30
4   5      23


In [103]:
'''
    Task 95:
    
    Drop multiple rows by row name
'''
print('Task 95:')  
numbers = pd.DataFrame({
    "id": [1, 2, 3, 4, 5, 6], 
    "number": [10, 20, 30, 30, 23, 12]
    
}, index=['one', 'two', 'three', 'four', 'five', 'six'])  
print(numbers)
numbers1 = numbers.drop(['two','six'])
print(numbers1)
numbers2 = numbers.drop('two')
print(numbers2)

Task 95:
       id  number
one     1      10
two     2      20
three   3      30
four    4      30
five    5      23
six     6      12
       id  number
one     1      10
three   3      30
four    4      30
five    5      23
       id  number
one     1      10
three   3      30
four    4      30
five    5      23
six     6      12


In [104]:
'''
    Task 96:
    
    Drop a single row
        
'''
print('Task 96:')  

Task 96:


In [105]:
'''
    Task 97:
        Get the the odd row
'''
print('Task 97:')  
x = numpy.array([
                    [ 1,  2,  3,  4,  5],
                    [ 6,  7,  8,  9, 10],
                    [11, 12, 13, 14, 15],
                    [16, 17, 18, 19, 20]
                ]
    )
print(x)
print(x[::2])

Task 97:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [106]:
'''
    Task 98:
        Get the even columns
'''
print('Task 98:')  
x = numpy.array([
                    [ 1,  2,  3,  4,  5],
                    [ 6,  7,  8,  9, 10],
                    [11, 12, 13, 14, 15],
                    [16, 17, 18, 19, 20]
                ]
    )
print(x)
print(x[:, 1::2])

Task 98:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]]


In [107]:
'''
    Task 99:
        Odd rows and even columns
'''
print('Task 99:')  

x = numpy.array([
                    [ 1,  2,  3,  4,  5],
                    [ 6,  7,  8,  9, 10],
                    [11, 12, 13, 14, 15],
                    [16, 17, 18, 19, 20]
                ]
    )
print(x)
print(x[::2, 1::2])

Task 99:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 2  4]
 [12 14]]


In [108]:
'''
    Task 100:
    
    Drop duplicates
'''
print('Task 100:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)
users.drop_duplicates('id', inplace=True)
print(users)

Task 100:
   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
   id      city  count
0   1   Toronto      7
2   2   Calgary      9
4   3  Montreal      7


In [109]:
'''
    Task 101:
    
    Drop all duplicates
'''
print('Task 101:')  
users = pd.DataFrame({
    "name": ['kevin', 'james', 'kumar', 'kevin', 'kevin', 'james'], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)
users.drop_duplicates('name', inplace=True, keep='last')
print(users)
users1 = users.drop_duplicates('name', keep=False)
print(users1)

Task 101:
    name      city  count
0  kevin   Toronto      7
1  james  Montreal      8
2  kumar   Calgary      9
3  kevin  Montreal      2
4  kevin  Montreal      7
5  james    Ottawa      8
    name      city  count
2  kumar   Calgary      9
4  kevin  Montreal      7
5  james    Ottawa      8
    name      city  count
2  kumar   Calgary      9
4  kevin  Montreal      7
5  james    Ottawa      8


In [110]:
'''
    Task 102:
        Multi Indexing:
'''
print('Task 102:')  

Task 102:


In [111]:
'''
    Task 103:
        Missing Data:
        Make A'th 3rd coulmn Nan
'''
print('Task 103:')  
df = pd.DataFrame(np.random.randn(6,1), index=pd.date_range('2013-08-01', periods=6, freq='B'), columns=list('A'))
print(df)
df.loc[df.index[3], 'A'] = np.nan
print(df)

Task 103:
                   A
2013-08-01  1.950254
2013-08-02 -0.586291
2013-08-05 -0.589643
2013-08-06  0.003645
2013-08-07 -1.621845
2013-08-08 -0.063462
                   A
2013-08-01  1.950254
2013-08-02 -0.586291
2013-08-05 -0.589643
2013-08-06       NaN
2013-08-07 -1.621845
2013-08-08 -0.063462


In [112]:
'''
    Task 104:
        
'''
print('Task 104:')
df1 = df.reindex(df.index[::-1]).ffill()
print(df1) 

Task 104:
                   A
2013-08-08 -0.063462
2013-08-07 -1.621845
2013-08-06 -1.621845
2013-08-05 -0.589643
2013-08-02 -0.586291
2013-08-01  1.950254


In [113]:
'''
    Task 105:
       Cumsum reset Nan
'''
print('Task 105:') 

Task 105:


In [114]:
'''
    Task 106:
'''
print('Task 106:')
df = pd.DataFrame([['http://wap.blah.com/xxx/id/11/someproduct_step2;jsessionid=....']],columns=['A'])
df1 = df['A'].str.findall("\\d\\d\\/(.*?)(;|\\?)",flags=re.IGNORECASE).apply(lambda x: pd.Series(x[0][0],index=['first']))
print(df1) 

Task 106:
               first
0  someproduct_step2


In [115]:
'''
    Task 107:
        Grouping:
'''
print('Task 107:')  
animals_df = pd.DataFrame({'animal': 'cat dog cat fish dog cat cat'.split(),
                   'size': list('SSMMMLL'),
                   'weight': [8, 10, 11, 1, 20, 12, 12],
                   'adult' : [False] * 5 + [True] * 2})
print(animals_df)

Task 107:
  animal size  weight  adult
0    cat    S       8  False
1    dog    S      10  False
2    cat    M      11  False
3   fish    M       1  False
4    dog    M      20  False
5    cat    L      12   True
6    cat    L      12   True


In [116]:
'''
    Task 108:
        Basic Group by
'''
print('Task 108:')  
animals_df1 = animals_df.groupby('animal').apply(lambda x: x['size'][x['weight'].idxmax()])
print(animals_df1)

Task 108:
animal
cat     L
dog     M
fish    M
dtype: object


In [117]:
'''
    Task 109:
       Get Group
'''
print('Task 109:')  
cats = animals_df.groupby(['animal']).get_group('cat')
print(cats)

Task 109:
  animal size  weight  adult
0    cat    S       8  False
2    cat    M      11  False
5    cat    L      12   True
6    cat    L      12   True


In [118]:
'''
    Task 110:
        
'''
print('Task 110:')
weights = animals_df.groupby(['weight']).get_group(20)  
print(weights)

Task 110:
  animal size  weight  adult
4    dog    M      20  False


In [119]:
'''
    Task 111:
        
'''
print('Task 111:')  
def GrowUp(x):
    avg_weight =  sum(x[x['size'] == 'series1'].weight * 1.5)
    avg_weight += sum(x[x['size'] == 'M'].weight * 1.25)
    avg_weight += sum(x[x['size'] == 'L'].weight)
    avg_weight /= len(x)
    return pd.Series(['L',avg_weight,True], index=['size', 'weight', 'adult'])

animals_df = pd.DataFrame({'animal': 'cat dog cat fish dog cat cat'.split(),
                   'size': list('SSMMMLL'),
                   'weight': [8, 10, 11, 1, 20, 12, 12],
                   'adult' : [False] * 5 + [True] * 2})

gb = animals_df.groupby(['animal'])

expected_df = gb.apply(GrowUp)
print(expected_df)

Task 111:
       size   weight  adult
animal                     
cat       L   9.4375   True
dog       L  12.5000   True
fish      L   1.2500   True


In [120]:
'''
    Task 112:
        Expanding Apply:
'''
print('Task 112:')  
series1 = pd.Series([i / 100.0 for i in range(1,6)])
print(series1)
def CumRet(x,y):
    return x * (1 + y)
def Red(x):
    return functools.reduce(CumRet,x,1.0)
s2 = series1.expanding().apply(Red)
# s2 = series1.expanding().apply(Red, raw=True) # is not working
print(s2)

Task 112:
0    0.01
1    0.02
2    0.03
3    0.04
4    0.05
dtype: float64
0    1.010000
1    1.030200
2    1.061106
3    1.103550
4    1.158728
dtype: float64


C:\ProgramData\Anaconda3.5\lib\site-packages\ipykernel_launcher.py:12: FutureWarning: Currently, 'apply' passes the values as ndarrays to the applied function. In the future, this will change to passing it as Series objects. You need to specify 'raw=True' to keep the current behaviour, and you can pass 'raw=False' to silence this warning
  if sys.path[0] == '':


In [121]:
'''
Task 113:
    Create Random integer between 0 to 100 with  10 itmes (2 rows, 5 columns)
'''
print('Task 113:')
df = pd.DataFrame(np.random.randint(0, 100, size=(3, 5)), columns=['Toronto', 'Ottawa', 'Calgary', 'Montreal', 'Quebec'])
print(df)

Task 113:
   Toronto  Ottawa  Calgary  Montreal  Quebec
0       16      30       50        23      34
1       48      56        4        58      93
2       53      73       13        67      79
